### ISSUE TITLE
[Discover] Narrow document details column

### ISSUE THREAD

**Issue by minjiewang29** [opensearch-project/OpenSearch-Dashboards#5683] opened 2024-01-11 14:11 UTC
- The area on the left takes up 1/3 of the entire page, but it's not that important，Main area on the right only take 2/3, What we are focusing on is the area on the right

1. suggestion：the area on the left is foldable, main area on the right can be maximized.

 
- if I want see the item detail, the UI popup is too small.

The previous interface was very good, I don’t know why it needs to be updated.

<img width="1478" alt="Screenshot 2024-01-11 at 09 07 31" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/16566170/02092dc3-1ce3-4e5d-8c92-3bb4252cdded">

**Comment by AMoo-Miki** [comment] 2024-01-11 18:06
Thanks @minjiewang29 for reaching out.

I am sure you would agree that different people have different purposes for using this interface and as such, something important to one person, might have the least importance to another. However, I believe the interface should offer the flexibility to be customized for each person's use. I think making the left-panel resizable would provide that flexibility; I also agree with you that making it collapsible might be desirable. I will discuss this with the maintainers. 

I was puzzled by the second issues you raised though: I cannot seem to find a way to reproduce it. Could you maybe help me reproduce this on [playground.opensearch.org](https://playground.opensearch.org). 

You also asked about the need to make the change: the old interface was using technologies that were outdated, discontinued, or had serious flaws in them. In order to provide you with the latest, safest, and most performant collection of technologies, OSD needed to recreate Discover from scratch.

The maintainers of OSD would love to make interfaces available to you that you enjoy using and find useful. We love to hear any comments or suggestions you have to make OSD the best tool for you and everyone else. Please don't hold back.

**Comment by minjiewang29** [comment] 2024-01-11 22:20
@AMoo-Miki 
Thanks for response.

Here is a screen recording showing the small  Document Details area.

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/16566170/37a3299c-6132-4457-8f7d-857bb82be81b

Looks like `Document Details` popup page have 2 columns，and the width of each column seems to be dynamically allocated.

<img width="1091" alt="Screenshot 2024-01-11 at 17 14 42" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/16566170/673f2ce9-44ff-4870-a2f4-da641e67d3fc">
<img width="1089" alt="Screenshot 2024-01-11 at 17 15 57" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/16566170/b8489187-a6ed-4cd7-a13d-e3a32190367f">


I hope opensearch become more better.

**Comment by kavilla** [comment] 2024-01-12 19:22
tagging @opensearch-project/opensearch-ux

**Comment by ashwin-pc** [comment] 2024-01-17 00:28
@minjiewang29 Thanks for opening this issue. Since the first of your two issues is being tracked in #4780 Do you mind if we repurpose this issue to track the other issue that you are seeing (The narrow document details column). Since the table is dynamically deciding the column with we may need to look into why under certain circumstances its causing the column to be that narrow. @ananzh Can you take a look at this when you have the chance?

**Comment by ananzh** [comment] 2024-01-19 18:16
@ashwin-pc @minjiewang29 I have assigned it to myself and will research on this. Since we are launching 2.12, I might schedule this work a bit late. Sorry about this but I have added to my priority list.

**Comment by AMoo-Miki** [comment] 2024-05-15 02:25
@minjiewang29 with the 2.14 release, the default interface of Discover has been adjusted to look more like the older interface. Please give it a try on https://playground.opensearch.org. We have a lot of exciting new features planned for this interface but for now, our goal was to eliminate the pain caused by the previous changes. I would love to hear about any remaining pain points you might have.

**Comment by ananzh** [comment] 2024-06-21 16:20
@minjiewang29 I think this is not an issue after 2.14. Resolve it for now. Feel free to re-open if there is any other issues.

**Closed by ananzh** 2024-06-21 16:20 UTC
Labels: bug, ux / ui, discover
