### ISSUE TITLE
[BUG] Flickering issue in Discover view when scrolled all the way down

### ISSUE THREAD

**Issue by stefansundin** [opensearch-project/OpenSearch-Dashboards#6188] opened 2024-03-19 00:15 UTC
**Describe the bug**

**To Reproduce**
1. Go to the Discover view.
2. Add a couple of columns. The more columns you have, the easier it is to trigger the issue (i.e. it happens at a wider window width if you have more columns).
3. Make sure your query finds some documents.
4. Scroll all the way down and you will get an epilepsy-inducing effect.
5. The issue only seems to be happening on the first page.
6. If the issue doesn't happen, try making the window narrower. I do this in the video below. When the window is larger you need to add more columns to trigger the flickering.

**Expected behavior**

When scrolling down to the bottom it should just stop normally without any flickering.

I also expect the space between the bottom of the table and the page navigation to be smaller. There is a lot of margin for some reason. This space also differs based on which page you are on.

**OpenSearch Version**
OpenSearch 2.11.0 hosted on AWS.

**Dashboards Version**
OpenSearch 2.11.0 hosted on AWS.

**Plugins**

No additional plugins.

**Screenshots**

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/1991151/064a4aeb-1355-4656-98c3-a37cac45144c

**Host/Environment (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 122

**Additional context**

**Comment by ashwin-pc** [comment] 2024-03-19 17:41
Closing as a duplicate of #5512

**Closed by ashwin-pc** 2024-03-19 17:41 UTC
Labels: bug, untriaged
