### ISSUE TITLE
[BUG] Dashboard replaces numbers in timestamp with zeros after decimal point

### ISSUE THREAD

**Issue by devdruggy** [opensearch-project/OpenSearch-Dashboards#3600] opened 2023-03-13 15:51 UTC
**Describe the bug**

An indexed record in opensearch with timestamp "2023-03-13T13:13:13.678668399Z" shows with timestamp "2023-03-13T13:13:13.678**000000**" in the dashboard.

**To Reproduce**
1. Go to 'DevTools'
2. Type the next code
```
PUT my-index-000001
{
  "mappings": {
    "properties": {
      "timestamp": {
        "type": "date"
      }
    }
  }
}

POST my-index-000001/_doc/
{
  "abc": "def",
  "timestamp": "2023-03-13T13:13:13.678668399Z"
}

GET my-index-000001/_search
```

4. Execute these blocks in sequence
5. On the last block you should see the record from block 2 with correct timestamp
6. Create an index pattern with timestamp field's format "Date nanos"
7. Go to 'Discover' and perform search
8. You should see the record from block 2 with incorrect timestamp with zeroes

**Expected behavior**
Value in the timestamp field must be same as source.

**OpenSearch Version**
v1.3.2 (AWS Managed)

**Dashboards Version**
v1.3.2 (AWS Managed)

**Screenshots**
<img width="604" alt="Снимок экрана 2023-03-13 в 18 46 43" src="https://user-images.githubusercontent.com/44507245/224754281-d95c553d-6fb0-46eb-83fd-e549c1c235e9.png">

**Comment by AMoo-Miki** [comment] 2023-03-14 18:55
@devdruggy thanks for reporting this issue. I was able to reproduce the issue on 2.6.0 and 1.3.8 as well.

Quickly peaking into it,
https://github.com/opensearch-project/OpenSearch-Dashboards/blob/d7004dc5b0392477fdd54ac66b29d231975a173b/src/plugins/discover/public/application/components/table/table.tsx#L49
... seems to not be doing the right thing.

**Comment by kavilla** [comment] 2023-05-11 17:28
This seems to be something that can be solved by documentation or hover over insight.

For me this works:

<img width="637" alt="Screenshot 2023-05-11 at 9 50 03 AM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/12060704/5cbbc425-6392-4242-8bc2-92e1668c8fec">

If you want to utilize `date nanos` on the field formatter on the index-pattern then the mapping on the index for that field should be of type `date_nanos`.

On the index mapping, if you were to pass `"format" : "strict_date_optional_time||epoch_millis"`, OpenSearch would have rejected the creation of the document as the format of the timestamp is not correct.  [[DOCS]](https://opensearch.org/docs/latest/field-types/date/).

Therefore within the Discover plugin, it sees that the index pattern is of type `date nanos` but the actually field type on the index is `date`. So the Discover plugin assumes that the value it got without any format on the field from OpenSearch was epoch milliseconds and tries to meet the requirements set by the user in the index pattern of `date nanos` and buffers the timestamp with trailing zeros. But in this case it overwrites the existing trailing values after milliseconds with zeroes in this process.

So in a way, Discover plugin is overcompensating here but it's assuming the type on the index pattern is the source of truth since it is set by the user and expects the data from OpenSearch to be "wrong".

**Action item**:

I do not believe this is a bug and working as expected. It seems like the current behavior is respecting a field formatter that is configurable and here the default formatter is replacing the fields.

I think the solution here is to repurpose this issue to show some indication somewhere like `You are mapping a date field to a date nanos field`. When first creating the index pattern the index pattern will default the value to the mapping type if you mapped it to date_nanos then the default value on the index pattern is date nanos, so we do know the mapping so perhaps something on the index pattern page to assist with this? 

cc: @KrooshalUX @kgcreative what do y'all think?

**Comment by devdruggy** [comment] 2023-05-16 08:24
Hi! Yes, your suggestion about the date_nanos index field type works! Thanks!

But have some things:
1. The date_nanos field type is missing from the [documentation](https://opensearch.org/docs/latest/field-types/supported-field-types/index/)
2. Based on your words it's strange that opensearch returns full-timestamp (with nanoseconds) when field type is date instead of date_nanos

**Comment by kavilla** [comment] 2023-05-16 19:21
> Hi! Yes, your suggestion about the date_nanos index field type works! Thanks!
> 
> But have some things:
> 
>     1. The date_nanos field type is missing from the [documentation](https://opensearch.org/docs/latest/field-types/supported-field-types/index/)
> 
>     2. Based on your words it's strange that opensearch returns full-timestamp (with nanoseconds) when field type is date instead of date_nanos

Correct. I think we can still classify this as a UX bug and will create a documentation issue.

**Comment by ashwin-pc** [comment] 2024-04-24 14:04
Closing this issue since the documentation has been updated. Feel free to reopen if that is no longer true.

**Closed by ashwin-pc** 2024-04-24 14:04 UTC
Labels: bug, good first issue
