### ISSUE TITLE
yarn opensearch snapshot error

### ISSUE THREAD

**Issue by ribalraza009** [opensearch-project/OpenSearch-Dashboards#3492] opened 2023-02-24 10:28 UTC
**Describe the bug**
I cloned the opensearch dashboard branch 1.2.0, yarn osd bootstrap went well but yarn opensearch snapshot gave the error
│ERROR uncaught exception in thread [main]
   │      java.lang.IllegalArgumentException: unknown setting [xpack.license.self_generated.type] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
   │            at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:589)
   │            at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:530)
   │            at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:500)
   │            at org.opensearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:470)
   │            at org.opensearch.common.settings.SettingsModule.<init>(SettingsModule.java:161)
   │            at org.opensearch.node.Node.<init>(Node.java:463)
   │            at org.opensearch.node.Node.<init>(Node.java:319)
   │            at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242)
   │            at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242)
   │            at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:412)
   │            at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:178)
   │            at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:169)
   │            at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:100)
   │            at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
   │            at org.opensearch.cli.Command.main(Command.java:101)
   │            at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:135)
   │            at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:101)

**Comment by ashwin-pc** [comment] 2023-02-24 22:15
Hey @ribalraza009, a few questions about the error that you are seeing:
1. Why are you working off the 1.2 branch? 1.3 is the latest supported version of the 1.x major release and most of the active development is happening in the main and 2.x branches. Is there a specific reason you are working on that branch?
2. I tried to reproduce your steps but did not face any issues. Can you give me any other suggestions on how i can reproduce the issue on my end? The steps i ran were:
    1.  `yarn osd clean`
    4. `yarn osd bootstrap`
    5. `yarn opensearch snapshot`

**Comment by ribalraza009** [comment] 2023-02-27 07:21
Hey @ashwin-pc , the issue is resolved, I think the other services and packages I was using on my linux were causing the trouble, once I restarted all the things again and set the development envoirnment, everything went well.

**Comment by ribalraza009** [comment] 2023-02-27 07:23
@ashwin-pc would you mind if I ask you about adding wazuh-kibana-app in my cloned repo. I am facing denpendecies version conflict

**Comment by ashwin-pc** [comment] 2023-03-01 18:50
@ribalraza009 `wazuh-kibana-app` is maintained by Wazuh. It might be more useful to raise an issue there for support. I'm not surprised that you have dependency conflicts since that plugin is built for Kibana and even though OpenSearch Dashboards is a fork of Kibana, we are two different products and the differences will only grow over time. So a plugin built for Kibana will have to be ported to work with OpenSearch Dashboards.

I'll close this issue however since the snapshot issue is resolved. Feel free to raise an issue if you have any other questions about Dashboards though.

**Closed by ashwin-pc** 2023-03-01 18:50 UTC
Labels: bug, needs more info
