### ISSUE TITLE
Create Smart Hyperlink Widget to Enable linking between OpenSearch Dashboards

### ISSUE THREAD

**Issue by terrywbrady** [opensearch-project/OpenSearch-Dashboards#4876] opened 2023-08-31 16:47 UTC
**Is your feature request related to a problem? Please describe.**

I have a number of OpenSearch dashboards available.  I would like to provide contextual navigation for users from one dashboard to another.

**Describe the solution you'd like**

Create a new visualization widget that generates hyperlinks to other dashboards.
- User can select the target dashboard for the hyperlink
- User can select the filters that will/will not be included in the hyperlink parameters
- User can set specific filter values that will be included in the hyperlink parameters
- User can select if the date range will be included in the hyperlink parameter OR the user can override the date range
- User can set the text for the hyperlink
- If a "series" is specified in the visualization, a list of hyperlinks may be generated for a set of TERM values

**Describe alternatives you've considered**

I have attempted to work around this with existing functionality.
- I have created a markdown dashboard that hyperlinks to other dashboards.  Unfortunately, the hyperlinks are fragile and the behavior of filters is not intuitive when navigating between dashboards.
- I have attempted to create a Notebook to accomplish my goal.  Currently, the Notebook requires end users to have some knowledge of query syntax in order to adjust a set of visualizations.

**Additional context**

**Comment by joshuarrrr** [comment] 2023-10-02 16:20
Hi @terrywbrady (nice meeting you at OpenSearchCon!)

Do you mind taking a look at https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1308? I think the drilldown list visualization design mostly covers what you mention here, although we may need to expand the definition a bit to account for filtering options. If that design isn't sufficient for the use case you have in mind, please add some additional comments over there.

**Comment by terrywbrady** [comment] 2023-10-02 20:00
@joshuarrrr , I took a closer look at #1308 and I think it encompasses my ideas.  I initially proposed this thinking it might be easier to implement, but I think #1308 describes a comprehensive solution.

Good to meet you as well.  I enjoyed the conference quite a bit.

**Comment by ashwin-pc** [comment] 2023-12-09 02:35
Closing this as a duplicate of #1308. Feel free to reopen if necessary

**Closed by ashwin-pc** 2023-12-09 02:35 UTC
Labels: enhancement
