### ISSUE TITLE
[BUG] 2.11 filtering indices list doesn't work as expected

### ISSUE THREAD

**Issue by ict-one-nl** [opensearch-project/OpenSearch-Dashboards#5319] opened 2023-10-18 13:46 UTC
**Describe the bug**

Latest release of Brave:

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/2643715/7aa89827-6fa9-4d74-891c-40124bb626ab

I need to press backspace first before I can search. 

**Expected behavior**
If I start to type I would have expected that the current * pattern was cleared and that the list is sorted or filtered and contains items that are relevant to the query instead of only high lighting the search phrase in the list.

**OpenSearch Version**
2.11

**Dashboards Version**
2.11

**Plugins**

S3 repo

**Screenshots**

N/A
**Host/Environment (please complete the following information):**
Default docker containers

**Additional context**

N/A

**Comment by zhongnansu** [comment] 2023-10-25 20:08
@mengweieric Hi Eric, could you help take a look at this? Is it related to the data source picker you added in recent release?

**Comment by dar9468** [comment] 2023-10-31 06:08
We're really looking forward to the solution

**Comment by dhumphries-sainsburys** [comment] 2023-11-15 16:13
Both myself and our users also find this change frustrating. I would go as far as to say if you only fix one thing for next release please let it be this

**Comment by abbyhu2000** [comment] 2023-11-15 19:49
This bug seems to be caused by this commit https://github.com/opensearch-project/OpenSearch-Dashboards/commit/1e980fac7a6dee3a1904511d2ae0f477575e6135. After removing the commit, the search functionality works fine. 

Could you take a look at this bug? @mengweieric 
Currently there is another issue open on this too: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5468

**Comment by amirkkn** [comment] 2023-11-20 11:32
This bug is really blocked us to release opensearch in prod, because most developers complained about that. 
Please consider it to be resolved in the next release. 
Thanks in Advance!

**Comment by camaeel** [comment] 2023-11-21 09:56
Really looking forward for this feature to work again. We have hundreds of indexes, and searching for one that is highlighted is tedious task.

**Closed** 2023-11-29 18:25 UTC
Labels: bug
