### ISSUE TITLE
Persist agg data when you switch between vis types

### ISSUE THREAD

**Issue by ashwin-pc** [opensearch-project/OpenSearch-Dashboards#2899] opened 2022-11-18 21:20 UTC

**Comment by abbyhu2000** [comment] 2023-01-04 22:25
After confirming with Ashwin, close this issue since it is a duplicate of : https://github.com/opensearch-project/OpenSearch-Dashboards/issues/2763

**Closed by abbyhu2000** 2023-01-04 22:25 UTC
Labels: vis builder, visualizations
