### ISSUE TITLE
Allow groups to be categorized within context menus

### ISSUE THREAD

**Issue by sikhote** [opensearch-project/OpenSearch-Dashboards#4073] opened 2023-05-22 06:23 UTC
**Is your feature request related to a problem? Please describe.**

We are looking for a solution to grouping context menu items a certain way. Currently, context menu items can be ordered or they can be grouped. When grouped, an item is added to the main menu that links to the panel of that group and is separated from other groups. We would like a way to group groups, essentially...a proposed name for this is a category...so that we can place groups next to each other that have the same category (see screenshot for example).

**Describe the solution you'd like**

A `category` option for a group, which allows other groups of the same category to be next to each other.

**Describe alternatives you've considered**

N/A

**Additional context**

This is related to https://github.com/opensearch-project/ux/issues/66 and would mostly be used to group together these context menu options: Alerting, Anomalies, and View Event.

<img width="296" alt="Screenshot 2023-05-25 at 10 24 26 PM" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/24573542/62ccb680-a192-4145-a3bf-434be29fac4e">

**Comment by joshuarrrr** [comment] 2023-05-22 19:32
The problem with this request is that it assumes a different API model, where plugin developers have a great deal of control over context menu items. The present abstraction (UI Actions) is not a context menu API, and it purposely abstracts away the context menu layout (or whether to even use a context menu component in the first place). So I think this needs to be approached from the perspective of:

1. What are our future plans for context menus (both generally, and on dashboard panels (@dagneyb, @KrooshalUX, @kgcreative ). 
2. Given the requirements for 1., is the existing API design for UI Actions sufficient, or do we need to redesign it for this type of use case.

**Comment by KrooshalUX** [comment] 2023-05-22 19:47
@joshuarrrr  this is a piggy back of what I have been discussing with you and @ashwin-pc  that UI actions doesn't sufficiently support what as released in OUI / vice versa. I think part of the issue is that the component design (within EUI) may have come after UI Actions was implemented. I am interested in trying to get UI actions and the component closer in support of eachother. We have visited this issue in the past when the Anywhere project began being implemented (we ran into this: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3303 

@sikhote  can you please follow up with a screenshot of the UI you are trying to support? 

Since this is not the first time we have run into this, and the UX was signed of in accordance of utilizing patterns from OUI components - I would like to see UI Actions expand to meet the necessary use cases that the OUI component solves for. @joshuarrrr can you help us outline the next steps to achieving that?

**Comment by sikhote** [comment] 2023-05-26 05:31
FYI I have updated the request with a new screenshot and wording that aligns with the coding approach.

**Closed** 2024-04-15 18:04 UTC
Labels: enhancement, ux / ui
