### ISSUE TITLE
[BUG][Discover] pattern with * as prefix it is not picking hidden index in discover

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#6809] opened 2024-05-19 02:29 UTC
**Describe the bug**

When we create an index pattern with prefix *, it is not picking up hidden index when selecting that index pattern in discover.

For example, when we created the index pattern `*index*` that can match 4 indices:
* 2 hidden indices `sample_index_1_hidden`, `sample_index_2_hidden`
* 2 normal indices `sample_index_1_not_hidden`, `sample_index_2_not_hidden`. 

When we go to discover, and select `*index*` in the datasource picker, `sample_index_1_hidden`, `sample_index_2_hidden` documents are not be able to show up in discover; only `sample_index_1_not_hidden`, `sample_index_2_not_hidden` documents will be shown.

However, if we created the index pattern and name it without using the * as the prefix, for example, `sample_index*`, then documents from all four indices will be shown.

**Comment by huyaboo** [comment] 2024-05-21 17:24
Need to verify if the call can be replicated in OpenSearch as well. If it cannot, this is a dashboards issue.

**Comment by seraphjiang** [comment] 2024-05-24 16:35
Thanks @abbyhu2000  @huyaboo for report the issue.
Although it is pretty clear to reproduce it, considering the purpose of hidden index is design for security and performance concern. this should be intended behavior regardless technical feasibility. I'm closing it as it is by design.

**Closed by seraphjiang** 2024-05-24 16:35 UTC
Labels: bug, discover

**Comment by dhumphries-sainsburys** [comment] 2024-12-17 13:48
@seraphjiang - Although you say this is by design it would be highly useful to be able to turn it on/off as required on a pattern basis. 

Our use case is we have some indexes with a lot of fields that we want to segment away from our general index pattern but still be able to search when required. Consider the below indexes where we essentially have 1 index per day per namespace

fluentd-foo-2024.12.16
fluentd-foo-2024.12.17
fluentd-bar-2024.12.16
fluentd-bar-2024.12.17
fluentd-vault-2024.12.16
fluentd-vault-2024.12.17

Currently we have the following index patterns in discover

fluentd-*
fluentd-foo-*
fluentd-bar-*
fluentd-vault-*

This has largely worked except fluentd-vault has a LOT of fields to the point that the field list cannot be refreshed on fluentd-* anymore as the payload is ~30MB and this is too much for opensearch to handle it seems. Our approach was to create all the fluentd-vault indices as hidden so that they don't appear in the fluentd-* pattern but have the fluentd-vault-* pattern able to search the hidden indices so that they are still possible to query by specifying the fluentd-vault-* pattern in the dropdown. This approach is specifically for the performance concern and there doesn't seem to be any other way around it
