### ISSUE TITLE
[Enhancement][UX] Option to set data source as default data source.

### ISSUE THREAD

**Issue by bandinib-amzn** [opensearch-project/OpenSearch-Dashboards#5868] opened 2024-02-13 20:49 UTC
**Is your feature request related to a problem? Please describe.**

As a user when there is only one data source created, it still asks me to select data source on dev tool, sample data screens. I want option to set data source as default data source and whenever there is option to select data source, I want that option to be selected by default.

**Comment by BionIT** [comment] 2024-04-03 21:21
This is duplicate of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6058, 6058 has been closed, should we close this?  @zhyuanqi

**Comment by zhyuanqi** [comment] 2024-04-03 21:23
Hi The issue has been addressed. Now customer can select default datasource. Also this default option would be received by the picker and selected as the default datasource. 
1) https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6186
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6237

**Comment by zhyuanqi** [comment] 2024-04-03 21:24
Yeah I believe we can close this.

**Comment by BionIT** [comment] 2024-04-03 21:36
Closed as duplicate

**Closed** 2024-04-03 21:36 UTC
Labels: enhancement, multiple datasource
