### ISSUE TITLE
[Dashboard De-Angular] Dashboard functionalities + Plugins Compatibility Test Campaign

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#4505] opened 2023-07-05 22:05 UTC
Compare and Test Dashboard Functionalities before and after De-Angular

**Comment by ananzh** [comment] 2023-07-05 22:08
<img width="1305" alt="Screenshot 2023-07-05 at 14 29 57" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/5c1f886a-2fc6-4895-a71e-ad005213b59c">

Might be just missing latest commits. Need to check on it.

**Comment by ananzh** [comment] 2023-07-05 22:43
## Test Dashboard using Observability Dashboard
* Verified that Dashboard has Observability Dashboard type
<img width="823" alt="Screenshot 2023-07-05 at 15 28 36" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/c1a76943-5497-48b4-93ff-1164b1850483">

* Verified that we could create a new Observability Dashboard directly from Dashboard
<img width="969" alt="Screenshot 2023-07-05 at 15 29 20" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/e615ae7b-072f-429e-b311-12076414db80">

* Verified that we could see the created Observability Dashboard directly from Dashboard
<img width="869" alt="Screenshot 2023-07-05 at 15 29 46" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/14decdf5-bb46-4299-aa4c-f270cf779eab">

* Found a bug that we could not delete Observability Dashboard directly from Dashboard. This is not a problem using older Dashboard. This only happens for Observability Dashboard.
<img width="1039" alt="Screenshot 2023-07-05 at 15 35 10" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/3d9834df-4970-40df-9907-e57d288fc131">

**Comment by abbyhu2000** [comment] 2023-07-05 23:06
> <img alt="Screenshot 2023-07-05 at 14 29 57" width="1305" src="https://user-images.githubusercontent.com/79961084/251293706-5c1f886a-2fc6-4895-a71e-ad005213b59c.png">
> Might be just missing latest commits. Need to check on it.

This is not a bug, this behavior is consistent with main. I believe the playground is showing that because it turn on a setting so the header is condensed. @ananzh

**Comment by pjfitzgibbons** [comment] 2023-07-06 17:06
Search needs to cover Type field as well.   This may not be a 1:1 from most-recent version of Dashboard List.
This "feature" is vetted by UX (@kgcreative ) as is needed to provide intuitive useage.

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/11318/5496afad-8b51-41d5-bdbd-b1fa67e7e7da)

 
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/11318/f3567259-9e75-4657-a4a0-e42c363eacfc)

Searching for "Observability" on the given list should return 1 result.

**Comment by kgcreative** [comment] 2023-07-06 19:22
+1 regarding searching over type & title here

**Comment by kavilla** [comment] 2023-07-12 04:06
Will be closing this as the only issue I saw appears to be related to another campaign.

Everything looking good on our side with plugins in the current 2.9 manifest.

**Closed by kavilla** 2023-07-12 04:06 UTC
