### ISSUE TITLE
[BUG] Discover missing metrics on refresh

### ISSUE THREAD

**Issue by seanneumann** [opensearch-project/OpenSearch-Dashboards#3029] opened 2022-12-05 00:43 UTC
**Describe the bug**

Relaying reported issues from Chris Lazzaro at Amazon...

My customer noticed a bug when he opens the discover screen from the OpenSearch Dashboards. I took a couple of snapshots.
Whenever they hit refresh after an hour or 30 minutes it missing the metrics of the first half hour or so until they refresh it again and then it's everything is fine. Anyone seen this before or if it's a known issue? It's not a show stopper for them but something my customer wanted to point out.

![image](https://user-images.githubusercontent.com/1413295/205526305-9b4eafa6-7757-4b9c-8b1b-d2b298d6e132.png)

**Comment by kavilla** [comment] 2022-12-06 08:29
@ananzh this feels vaguely familiar. Do you remember if we looked into something like this before?

**Comment by ananzh** [comment] 2022-12-12 22:03
Hi I would like to ask for more detailed steps. I think the issue is that customer doesn’t set auto refresh. Therefore, customer only sees a refresh to fetch the correct data when he/she manually click the refresh button.

**Comment by manasvinibs** [comment] 2023-01-17 18:14
Based on the information provided here in the issue, we think this is working as expected. We would require more details, if the issue persist. We are closing this for now, Please feel free to re-open if the issue is persistent.

**Closed by manasvinibs** 2023-01-17 18:14 UTC
Labels: bug, needs more info, discover
