### ISSUE TITLE
[BUG] Error when using table vis in Vis Builder

### ISSUE THREAD

**Issue by abbyhu2000** [opensearch-project/OpenSearch-Dashboards#3394] opened 2023-02-07 16:15 UTC
**Describe the bug**

When trying to use table visualization type in Vis Builder, there is an error saying `[opensearch_dashboards_table] > Cannot read properties of undefined (reading 'splitColumn')`. I only added one field `average_product.base_price` here as shown below. 
I did not see this error previously when using table vis.
![Screen Shot 2023-02-07 at 8 12 38 AM](https://user-images.githubusercontent.com/43937633/217300062-f88d5b95-4e61-426a-bd99-83fe744a1275.png)

**To Reproduce**
1. Go to Vis builder
2. Change vis type to table
3. Add a field under metric

**Comment by ananzh** [comment] 2023-02-07 20:03
I am not able to reproduce it in main.
Let me pull an OS 2.5 and try it.
@abbyhu2000 which version did you see the error? main or or 2.4 or 2.5?

**Comment by ananzh** [comment] 2023-02-07 20:07
can't reproduce it in 2.5

<img width="1769" alt="Screenshot 2023-02-07 at 12 06 16" src="https://user-images.githubusercontent.com/79961084/217353496-813ec5e9-f595-46e1-bef2-447d3c3647a5.png">

@abbyhu2000 let me sync up with you to help me reproduce it

**Comment by abbyhu2000** [comment] 2023-02-08 00:25
Sorry I should be more specific, I had this error on the 2.4 branch, and i do not have this issue on 2.5 branch. Maybe it is fixed after 2.5 release? @ananzh

**Comment by ashwin-pc** [comment] 2023-02-28 00:35
@abbyhu2000 no we do not. Since this bug no longer exists on main or on any of the supported branches, i'd close this issue

**Closed** 2023-02-28 00:40 UTC
Labels: bug, vis builder, tableVis
