### ISSUE TITLE
[BUG] Make running version compatible with Beat to use API to import dashboards

### ISSUE THREAD

**Issue by seraphjiang** [opensearch-project/OpenSearch-Dashboards#939] opened 2021-11-15 22:52 UTC
**Describe the bug**

When we forked OpenSearch Dashboards, we change the dashboards version from 7.10 to 1.0. This cause incompatible issue to use `metricbeat` to import dashboards through API

```2021-11-15T21:17:36.997Z	ERROR	instance/beat.go:956	Exiting: Kibana API is not available in Kibana version 1.1.0 ```

this is due to the client compatibility check in beat

**To Reproduce**

use metricsbeat to import Dashboards
https://github.com/elastic/beats/blob/8a5dac67f9c9a50c66cc62835c7ca94da05ba030/libbeat/dashboards/dashboards.go#L98

```
cat logs/metricbeat
2021-11-15T21:17:36.300Z	INFO	instance/beat.go:645	Home path: [/home/ec2-user/metricbeat] Config path: [/home/ec2-user/metricbeat] Data path: [/home/ec2-user/metricbeat/data] Logs path: [/home/ec2-user/metricbeat/logs]
2021-11-15T21:17:36.304Z	INFO	instance/beat.go:653	Beat ID: 1569388c-851b-48b3-b1d9-e2e27daaff04
2021-11-15T21:17:36.309Z	INFO	[beat]	instance/beat.go:981	Beat info	{"system_info": {"beat": {"path": {"config": "/home/ec2-user/metricbeat", "data": "/home/ec2-user/metricbeat/data", "home": "/home/ec2-user/metricbeat", "logs": "/home/ec2-user/metricbeat/logs"}, "type": "metricbeat", "uuid": "1569388c-851b-48b3-b1d9-e2e27daaff04"}}}
2021-11-15T21:17:36.309Z	INFO	[beat]	instance/beat.go:990	Build info	{"system_info": {"build": {"commit": "aacf9ecd9c494aa0908f61fbca82c906b16562a8", "libbeat": "7.10.2", "time": "2021-01-12T23:22:57.000Z", "version": "7.10.2"}}}
2021-11-15T21:17:36.309Z	INFO	[beat]	instance/beat.go:993	Go runtime info	{"system_info": {"go": {"os":"linux","arch":"amd64","max_procs":2,"version":"go1.14.12"}}}
2021-11-15T21:17:36.312Z	INFO	[add_cloud_metadata]	add_cloud_metadata/add_cloud_metadata.go:93	add_cloud_metadata: hosting provider type detected as aws, metadata={"account":{"id":"178161197791"},"availability_zone":"eu-west-1a","image":{"id":"ami-09d4a659cdd8677be"},"instance":{"id":"i-09f09938e495f44f4"},"machine":{"type":"t3.small"},"provider":"aws","region":"eu-west-1"}
2021-11-15T21:17:36.312Z	INFO	[beat]	instance/beat.go:997	Host info	{"system_info": {"host": {"architecture":"x86_64","boot_time":"2021-11-15T00:14:48Z","containerized":false,"name":"ip-10-0-46-162.eu-west-1.compute.internal","ip":["127.0.0.1/8","::1/128","10.0.46.162/18","fe80::4de:3ff:fef8:f2f7/64"],"kernel_version":"4.14.252-195.483.amzn2.x86_64","mac":["06:de:03:f8:f2:f7"],"os":{"family":"redhat","platform":"amzn","name":"Amazon Linux","version":"2","major":2,"minor":0,"patch":0,"codename":"Karoo"},"timezone":"UTC","timezone_offset_sec":0,"id":"301515433eac4dc09be11e8290ffda56"}}}
2021-11-15T21:17:36.312Z	INFO	[beat]	instance/beat.go:1026	Process info	{"system_info": {"process": {"capabilities": {"inheritable":null,"permitted":null,"effective":null,"bounding":["chown","dac_override","dac_read_search","fowner","fsetid","kill","setgid","setuid","setpcap","linux_immutable","net_bind_service","net_broadcast","net_admin","net_raw","ipc_lock","ipc_owner","sys_module","sys_rawio","sys_chroot","sys_ptrace","sys_pacct","sys_admin","sys_boot","sys_nice","sys_resource","sys_time","sys_tty_config","mknod","lease","audit_write","audit_control","setfcap","mac_override","mac_admin","syslog","wake_alarm","block_suspend","audit_read"],"ambient":null}, "cwd": "/home/ec2-user/metricbeat", "exe": "/home/ec2-user/metricbeat/metricbeat", "name": "metricbeat", "pid": 6608, "ppid": 4251, "seccomp": {"mode":"disabled","no_new_privs":false}, "start_time": "2021-11-15T21:17:35.710Z"}}}
2021-11-15T21:17:36.312Z	INFO	instance/beat.go:299	Setup Beat: metricbeat; Version: 7.10.2
2021-11-15T21:17:36.312Z	INFO	[index-management]	idxmgmt/std.go:184	Set output.elasticsearch.index to 'metricbeat-7.10.2' as ILM is enabled.
2021-11-15T21:17:36.312Z	INFO	eslegclient/connection.go:99	elasticsearch url: http://localhost:9200
2021-11-15T21:17:36.313Z	INFO	[publisher]	pipeline/module.go:113	Beat name: ip-10-0-46-162.eu-west-1.compute.internal
2021-11-15T21:17:36.347Z	INFO	kibana/client.go:119	Kibana url: http://k8s-default-ingressd-ea59b29e5c-1739843568.eu-west-1.elb.amazonaws.com:80
2021-11-15T21:17:36.990Z	INFO	kibana/client.go:119	Kibana url: http://k8s-default-ingressd-ea59b29e5c-1739843568.eu-west-1.elb.amazonaws.com:80
2021-11-15T21:17:36.997Z	ERROR	instance/beat.go:956	Exiting: Kibana API is not available in Kibana version 1.1.0
```

**Expected behavior**

We fixed OpenSearch to send 7.10.2 in compatibility mode. We should do the same in Dashboards

Refer to
https://github.com/opensearch-project/OpenSearch/pull/898

Option A (preferred):

Provide a settings in dashboards advanced settings, provide a way to override dashboards version for compatibility

Option B:

Provide a config item in kibana.yml to override dashboards version.

**Comment by kavilla** [comment] 2021-11-16 00:42
Believe this a duplicate of: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/831

There is currently a workaround:
https://github.com/opensearch-project/OpenSearch-Dashboards/issues/656#issuecomment-898575767

One hesitation even if we fake the version number will there be continued support from metricbeat?

**Closed** 2021-11-16 19:53 UTC
Labels: bug, untriaged

**Comment by jacobabraham** [comment] 2021-11-17 02:57
Why is this closed? is there a solution other than the workaround?

**Comment by tmarkley** [comment] 2021-11-23 15:27
> Why is this closed? is there a solution other than the workaround? or is it because it is a duplicate?

Yeah, as @kavilla mentioned above, it's a duplicate.
