### ISSUE TITLE
[BUG] Possible race condition when running build clean empty folder task on Mac OS

### ISSUE THREAD

**Issue by DanielBelmes** [opensearch-project/OpenSearch-Dashboards#2847] opened 2022-11-09 19:39 UTC
**Describe the bug**

In `src/dev/build/lib/fs.ts deleteEmptyFolders` there is a race condition that can occur with the [del library](https://github.com/sindresorhus/del/issues/68) that will cause an error to be thrown(similar one referenced in the link to bug.) 

**To Reproduce**
1. Run build on Mac OS
2. At end of build when clean empty folders is run you might see error with some of the build files being deleted.

**Expected behavior**
The expectation is that the build succeeds without fail.

**OpenSearch Version**
N/A

**Dashboards Version**
All current versions applicable

**Plugins**
N/A

**Screenshots**
N/A

**Host/Environment (please complete the following information):**
 - OS: Mac OS
 - Browser and version: Chrome 107.0.5304.110

**Additional context**

Version 6.1.1 of del is the latest version this repo can update to without having to change any existing code and to fix this bug.

**Comment by seanneumann** [comment] 2022-11-10 22:18
Thanks @DanielBelmes for submitting the issue. Would you like to try to solve this? We'd love to support your contribution!

**Comment by DanielBelmes** [comment] 2022-11-13 08:38
Hey thank you so much. Sorry for getting back to you a little slowly. I was just behind on emails. Didn't wanna submit a PR until someone had a look at the ticket. @seanneumann are you guys alright with me just updating the packages across the board? I believe when I did the change locally on just the main package.json to test it out there was a build error that every module needed it updated within their package.json.

**Comment by zhongnansu** [comment] 2022-11-14 19:17
cc @AMoo-Miki , you may have more knowledge on the build system

**Comment by joshuarrrr** [comment] 2022-11-14 19:33
> are you guys alright with me just updating the main and module(/packages) package.jsons and locks across the board? I believe when I did the change locally on just the main package.json to test it out there was a build error that every module(/packages) needed it updated within their package.json. Sorry trying to mix typical jargon and OSD jargon.

@DanielBelmes it's a little hard to say without seeing the change - are you saying the issue is in the way the `clean` or `extraPatterns` are defined? Or do we need to change the implementation of the script responsible for that task?

**Comment by DanielBelmes** [comment] 2022-11-14 22:03
@joshuarrrr No nothing fancy needed. They fixed the implementation in version 6.1.1 of del. Just a simple package update. Let me eat lunch and ill just whip up the PR really quickly and you can take a look. I’ve verified it fixes the issue as well.

**Comment by joshuarrrr** [comment] 2023-03-10 21:47
closed via #2873

**Closed by joshuarrrr** 2023-03-10 21:47 UTC
Labels: bug, os - mac
