### ISSUE TITLE
Get the number of data source for empty state for aggregated view

### ISSUE THREAD

**Issue by yujin-emma** [opensearch-project/OpenSearch-Dashboards#6562] opened 2024-04-19 21:23 UTC
**Is your feature request related to a problem? Please describe.**

![empty-state-broken-aggregated-view](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/112784385/66c468e5-f991-4835-a947-b2826ff0bf9e)

**Describe the solution you'd like**

Provide the number of data source for empty state, just give it 0 since it is empty state

**Describe alternatives you've considered**

**Additional context**

**Comment by BionIT** [comment] 2024-04-22 21:48
This is duplicate of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6565, close as this PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6597 will address 6565

**Closed by BionIT** 2024-04-22 21:48 UTC
Labels: enhancement
