### ISSUE TITLE
[Bug]: Filter by type is by default 3, it should be 0.

### ISSUE THREAD

**Issue by kritikag35** [opensearch-project/OpenSearch-Dashboards#5651] opened 2023-12-27 09:54 UTC
### Describe the bug

Filter by type by default is 3, and if we select 3 filters in it , it is 3 with highlighted red color. 
It seems like it will be difficult for a colour-blind person to differentiate the two. earlier it used to be 0 which did specify that how many filters are selected.

Attached are the file which shows without selecting and with selecting the filters.

With 3 filters selected:
![filter_by_type_3_selected](https://github.com/opensearch-project/opensearch-build/assets/44207411/dd7569c2-3bcd-43f1-aef8-cdf72c26bc4c)

With no filter selected:
![filter_by_type_3](https://github.com/opensearch-project/opensearch-build/assets/44207411/e10c4714-38bb-4b5e-b3a1-4e8bdeddf73b)

### To reproduce

- Go to Discover and click on any index pattern from the dropdown list.
- See default value of Filter by type with selected all 3 filters and then without selecting any filter.
- You will see that both time it is 3.

### Expected behavior

There should be some difference between when all 3 filters selected and when none , as it is difficult for a colour-blind person to differentiate.

Earlier it used to be as shown in the files attached.

### Screenshots

Old version
![image](https://github.com/opensearch-project/opensearch-build/assets/44207411/2c087d83-fa8f-43ad-abf6-a74abc66fb67)

New Version
![image](https://github.com/opensearch-project/opensearch-build/assets/44207411/5f5a97bc-f70d-4b1b-959d-7a3060fea8bb)

**Comment by kavilla** [comment] 2024-01-09 18:14
looks like a duplicate of: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5651.

Will close in favor of the earlier one.

**Closed by kavilla** 2024-01-09 18:14 UTC
Labels: bug, untriaged
