### ISSUE TITLE
[BUG] Blank "dashboardViewport"

### ISSUE THREAD

**Issue by untitledds** [opensearch-project/OpenSearch-Dashboards#5274] opened 2023-10-11 14:10 UTC
**Blank dashbord page**
After upgrade Opensearch and Opensearch Dashboards from 2.8 to 2.10 i have error:
When you open any dashboard using links from a markdown visualization, there is an empty space instead of the dashboard if you refresh the page without using the cache (Ctrl + Shift + R) then the dashboard opens. Repeats in any browser and in incognito mode. In html, inside "div id="dashboardViewport"" is empty. At the same time, errors appear in the java console: "Error: Search scope not defined", "Uncaught Error: Search scope not defined", "Detected an unhandled Promise rejection.
Error: Embeddable has been destroyed", "Uncaught (in promise) Error: Embeddable has been destroyed"
When opening from the dashboard page (http://localhost:5601/app/dashboards#/list )the dashboard most likely opens normally.
When opening from navmenu (Recently viewed) for the most part the error is reproduced.

**To Reproduce**
1. Create dashboards with any content
2. Create a Markdown type visualization
3. Create links to the created dashboards in the visualization
4. Add visualization to dashboards
5. Open the dashboard.
6.Follow the link to another dashboard
7. Instead of visualization, there will be an empty page

**Expected behavior**

**OpenSearch Version**
2.10.0.

**Dashboards Version**
2.10.0

**Plugins**

All default installed plugin
alertingDashboards@2.10.0.0
anomalyDetectionDashboards@2.10.0.0
customImportMapDashboards@2.10.0.0
ganttChartDashboards@2.10.0.0
indexManagementDashboards@2.10.0.0
mlCommonsDashboards@2.10.0.0
notificationsDashboards@2.10.0.0
observabilityDashboards@2.10.0.0
queryWorkbenchDashboards@2.10.0.0
reportsDashboards@2.10.0.0
searchRelevanceDashboards@2.10.0.0
securityAnalyticsDashboards@2.10.0.0
securityDashboards@2.10.0.0

**Screenshots**
![screen](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/7485765/061e9909-ee68-4c9f-ab58-a5d3e4641b09)

**Host/Environment (please complete the following information):**
 - OS: Windows 10.0.19045
 - Browser and version: MS Edge 117.0.2045.47, Firefox 118.0.2 

**Additional context**

**Comment by ananzh** [comment] 2023-10-11 19:53
I have reproduced the issue. Here is a screen record

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/79961084/e1921033-9da8-4b08-90bd-3ababc5f54ae

The url seems correct to me. I do see an empty page but if refresh we could see dashboard loaded correctly. Therefore the url has no issue.

**Comment by BigSamu** [comment] 2023-10-11 21:58
@ananzh give this issue. I will take a look to it.

**Comment by ananzh** [comment] 2023-10-11 22:37
> @ananzh give this issue. I will take a look to it.

It is urs~

**Comment by kavilla** [comment] 2023-10-12 21:36
Likely a duplicate of this: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4694#issuecomment-1702271190

Direct navigation from one dashboard to another dashboard requires a browser reload.

**Comment by BigSamu** [comment] 2023-10-13 09:37
@ananzh should we merge this issue with issue #4694? Not sure how is the process here. @kavilla are you currently working on this issue? Have you already made a PRs?

Regards,

Samuel

**Comment by ananzh** [comment] 2023-10-23 16:03
@BigSamu I have added you to #4694. Close this one.

**Closed by ananzh** 2023-10-23 16:03 UTC
Labels: bug, good first issue, v2.12.0
