### ISSUE TITLE
[BUG] onSelectedDataSources not acting as expected for DataSourceMenu selectable

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/OpenSearch-Dashboards#6367] opened 2024-04-08 14:45 UTC
**Describe the bug**

There is a bug that DataSourceMenu selectable view is always setting the selected datasource as the default one, even after user select otherwise. 

In my local code, console log shows that I select a local cluster (default is 9202):
```
{
    "id": "",
    "label": "Local cluster"
}
```

In `DataSourceMenu` component, this is successfully logged out as the activeOption

```
[
    {
        "id": "",
        "label": "Local cluster"
    }
]
```

In DataSourceSelectable component, after getDefaultDatasource function it changes back to the default:

```
[
    {
        "id": "94ffa650-f11a-11ee-a585-793f7b098e1a",
        "label": "9202"
    }
]
```

Can reproduce this by setting up datasource menu with multiple option, and use the selectable config, and try to select anything that isn't the default. The onSelectedDataSources function will keep on outputting the default even after you select something different.

**Comment by yujin-emma** [comment] 2024-04-08 15:46
Hi, @derek-ho , for case 3, could you also please provide the dataSourceOption list, just want to confirm 

```
[
    {
        "id": "94ffa650-f11a-11ee-a585-793f7b098e1a",
        "label": "9202"
    }
]
```

exist in the datsSourceOption list and dataSourceId is valid

**Comment by derek-ho** [comment] 2024-04-08 15:59
Hi @yujin-emma sorry for the confusion - these are not 3 cases that I am testing, it is one case - basically I am selecting a different option other than the default, and it is being passed fine at least into the datasourcemenu component. However, within the datasourceselectable component it is somehow getting reset to the default one, even if passed in activeoption

**Comment by derek-ho** [comment] 2024-04-09 14:54
@yujin-emma @zhongnansu I just pulled main and the bug is gone - if changes were made that address this I think we can close?

**Comment by zhongnansu** [comment] 2024-04-09 16:52
> @yujin-emma @zhongnansu I just pulled main and the bug is gone - if changes were made that address this I think we can close?

couldn't reproduce, I tried DataSourceSelectable in  example plugin, it successfully print out the selected data source instead of default . Closing for now If there's still issue, feel free to reopen.
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/32652829/ee45d7a2-65f9-4c66-b271-fdd11514f523)

**Closed by zhongnansu** 2024-04-09 16:52 UTC
Labels: bug, untriaged
