### ISSUE TITLE
[BUG] Make triple quoting output in console

### ISSUE THREAD

**Issue by ohtaeg** [opensearch-project/OpenSearch-Dashboards#3617] opened 2023-03-16 11:56 UTC
**Describe the bug**
- I'm building a pipeline and loading data into OpenSearch. (filebeat -> logstash -> opensearch)
- When data is queried, the console reformats the output using three quoted strings if the value contains a new line.

<br>

 logstash output 
```
{
  "message": "triple\nquotes"
}
```
opensearch would be reformated to:
```
{
  "message": """triple
quotes"""
}
```

The logstash settings are as follows.
```yaml
input {
  beats {
    port => 5044
  }
}

output {
  stdout { codec => json }

  opensearch {
    hosts =>  [""]
    user  =>  ""
    password  =>  ""
    index => "log-%{+YYYYMMdd}"
    ssl => true
    ecs_compatibility => "disabled"
  }
}
```

- I think there was a similar problem in Kibana. (see [forums](https://discuss.elastic.co/t/triple-quotes/111902))

<br>

**To Reproduce**
1. Send data from logstash to opensearch
2. Go to Opensearch Dashboards Dev tools
3. Search
4. See result
<img width="491" alt="image" src="https://user-images.githubusercontent.com/20432323/225606475-476f68a8-cb8f-42c8-b7cf-666c1e4b71e5.png">

**OpenSearch Version**
- [Opensearch 2.3](https://opensearch.org/docs/2.3/install-and-configure/install-opensearch/index/)

**Dashboards Version**
- [Opensearch Dashboard 2.3](https://opensearch.org/docs/2.3/install-and-configure/install-dashboards/index/)

**Logstash Version**
- [logstash-oss-with-opensearch-output-plugin-7.16.3-linux-x64](https://opensearch.org/artifacts#:~:text=x64.tar.gz-,logstash%2Doss%2Dwith%2Dopensearch%2Doutput%2Dplugin,-docker%2Darm64)

**Plugins**
- x

**Host/Environment (please complete the following information):**
 - OS:
     -  Amazon Linux2 (5.10.167-147.601.amzn2.x86_64)
 - Browser and version:
     - Chrome 111.0.5563.64 (x86_64) 

**Additional context**
- Please let me know if I miss anything.

**Comment by abbyhu2000** [comment] 2023-03-21 00:04
@ohtaeg Thanks for opening this issue! 

After investigation, this is not a bug. You can enable or disable the triple quote feature by toggling the settings `use triple quotes in output pane` in the console setting.

<img width="686" alt="Screen Shot 2023-03-20 at 5 04 32 PM" src="https://user-images.githubusercontent.com/43937633/226491175-afcae6bb-f8ac-4202-8964-0a44199f5042.png">

<img width="968" alt="Screen Shot 2023-03-20 at 5 02 10 PM" src="https://user-images.githubusercontent.com/43937633/226490903-9d86378f-e5e2-4a29-934e-c4f7f61249c7.png">

**Comment by abbyhu2000** [comment] 2023-03-21 00:07
Close the issue as solution has been provided. Please reopen the issue if there are further questions.

**Closed by abbyhu2000** 2023-03-21 00:07 UTC
Labels: bug, untriaged

**Comment by ohtaeg** [comment] 2023-03-21 02:36
Thank you for your kind reply!! :)
