### ISSUE TITLE
[BUG] OSD fails to start with OpenSearch cluster in rolling upgrade

### ISSUE THREAD

**Issue by shdubsh** [opensearch-project/OpenSearch-Dashboards#590] opened 2021-07-02 20:25 UTC
**Describe the bug**

OpenSearch-Dashboards fails to start while the cluster is transitioning to OpenSearch.  This renders Kibana and OpenSearch-Dashboards unavailable for the duration of the upgrade.  For clusters with a lot of data to move or large clusters, this could manifest as a long maintenance window or outage.

**To Reproduce**

1. Bootstrap ES (OSS) 7.10 cluster.
2. Join OpenSearch node to ES cluster.
3. Install OpenSearch-Dashboards on OpenSearch node.
4. Start OpenSearch-Dashboards and tail the log.
5. Observe `{"type":"log","@timestamp":"2021-07-02T19:53:50Z","tags":["error","savedobjects-service"],"pid":14817,"message":"This version of OpenSearch Dashboards (v1.0.0-SNAPSHOT) is incompatible with the following OpenSearch nodes in your cluster: v7.10.2 @ 172.16.4.117:9200 (172.16.4.117), v7.10.0 @ 172.16.4.21:9200 (172.16.4.21)"}`
6. Run `curl localhost:5601`
7. Observe `OpenSearch Dashboards server is not ready yet`

**Expected behavior**
OpenSearch-Dashboards should function against a transitioning-to-OpenSearch 1.0 cluster.

**OpenSearch Version**

Tried both

- 1.0.0-rc1
- 1.1.0-SNAPSHOT@8082604ec273ffdb50046f53af3d2553a106c9fb

**Dashboards Version**
1.0.0-SNAPSHOT@45df886890f2039d88f9675d401f2c7c85ce781e

**Plugins**

None

**Screenshots**

N/A

**Host/Environment**
 - OS: Debian Buster

**Additional context**

The two nodes referenced in the above error message are the two remaining ES nodes of a 5-node cluster.

I also tried kibana-oss 7.10 and received a similar error message: `{"type":"log","@timestamp":"2021-07-02T20:16:31Z","tags":["error","savedobjects-service"],"pid":15725,"message":"This version of Kibana (v7.10.0) is incompatible with the following Elasticsearch nodes in your cluster: v1.0.0 @ 172.16.1.86:9200 (172.16.1.86), v1.1.0 @ 172.16.2.223:9200 (172.16.2.223), v1.0.0 @ 172.16.3.147:9200 (172.16.3.147)"}`

**Comment by kavilla** [comment] 2021-07-06 17:31
Hey @shdubsh! Unfortunately, this is a known issue.

> In the same way as Kibana OSS, OpenSearch Dashboards does not support rolling upgrades, but it supports restart upgrades. You are able to stop all Kibana OSS instances, deploy a new OpenSearch Dashboards instance and direct traffic to it. [[source](https://opensearch.org/faq/#q3.1)]

If you do not mind, I will close as a duplicate of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/365, but will reference it because you raise a really good point. 

The upstream prevented multiple versions for a rolling upgrade due a saved object's structure changing potentially causing data loss, although running the engines should be accessible.

> For clusters with a lot of data to move or large clusters, this could manifest as a long maintenance window or outage.

I believe the sentiment is shared but some R&D for a better customer experience.

**Closed by kavilla** 2021-07-06 17:31 UTC
Labels: bug
