### ISSUE TITLE
[BUG] Table visualisations sometimes show results in a small scrollable portion of the screen

### ISSUE THREAD

**Issue by jgough** [opensearch-project/OpenSearch-Dashboards#3737] opened 2023-03-30 12:43 UTC
**Describe the bug**

When viewing many results in a table visualisation, these are only shown in a small area of the screen

**To Reproduce**
1. Open any table visualisation split by rows with a default size of 5 _-or-_  Go to [this Sandbox Page](https://playground.opensearch.org/app/visualize?#/create?type=table&savedSearchId=571aaf70-4c88-11e8-b3d7-01146121b73d&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1y,to:now))&_a=(filters:!(),linked:!t,query:(language:kuery,query:''),uiState:(),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(field:DistanceMiles,json:'000',missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!f,otherBucketLabel:Other,size:5),schema:bucket,type:terms)),params:(perPage:10,percentageCol:'',showMetricsAtAllLevels:!f,showPartialRows:!f,showTotal:!f,totalFunc:sum),title:'',type:table)))

2. Inside the _Split rows_ bucket, change the _Size_ to **100**
3. Click on Update.  More rows should be shown but it should be paginated.
4. Click on _Options_ in the side panel
5. Change _Max rows per page_ to **100**
6. Note that only 10 rows are shown, but the data table is actually scrollable with the mouse wheel to view 100 results within the small window:

![image](https://user-images.githubusercontent.com/968442/228838320-e8fe362f-53ac-4ed4-975e-701230ffd3ec.png)

**Expected behavior**
If you perform the steps above and copy the current URL and paste into a new tab you get the expected behaviour which is a table showing more than 10 rows:

![image](https://user-images.githubusercontent.com/968442/228838849-e9f9fcac-2f87-4f4d-83e7-3ccc6d10b0e8.png)

**OpenSearch Version**
2.6.0

**Dashboards Version**
2.6.0

**Additional context**
Reproduced in Edge 111.0.1661.54 and Firefox 102.9.0esr (64-bit)

**Comment by joshuarrrr** [comment] 2023-03-31 23:31
Interesting - I'm actually having a little difficulty reproducing that exact behavior, but there's definitely a bug here with the viz sizing and pagination. Thanks for reporting - we'll take a look.

**Comment by joshuarrrr** [comment] 2023-03-31 23:33
@ananzh I tagged this as 2.7 - I'm not sure if that will be possible, but that's probably what we should aim for.

**Comment by jgough** [comment] 2023-04-01 08:55
@joshuarrrr I have updated the repro instructions above, I think I had the steps the wrong way around, apologies.

**Comment by curq** [comment] 2023-04-01 13:54
I have researched this bug, and was able to reproduce it.

The problem seems to lie within EuiDataGrid component, specifically EuiDataGridBody. It seems like for some reason ResizeObserver is not working/reacting on initial load. When the number of row changes the value remains the same as in the screenshot, 375 is a default height.
<img width="1042" alt="Bug" src="https://user-images.githubusercontent.com/67782303/229292821-502b9ab4-9063-4742-a48d-a10627f04edd.png">

To test it I have opened the same page in the new tab and here the ResizeObserver does work, and height changes after every update of number of rows. Below is the screenshot from the new tab. I also noticed that the state that I assume responsible for the height is 0 in this case.
<img width="517" alt="Working" src="https://user-images.githubusercontent.com/67782303/229293061-c7b3644c-8049-4645-a3c8-b98bbf348075.png">

I'm currently not sure how to solve but as I am not familiar with the eui, I will try to look into this more.

**Comment by ananzh** [comment] 2023-04-04 15:35
@curq @jgough thanks for opening the issue and provide some initial thoughts. Kudos to @curq's finding and yes `euiDataGrid__virtualized` class in the `EuiDataGrid` is used to create a virtualized data grid that can efficiently handle large amounts of data. By default, this `euiDataGrid__virtualized` class will adjust its height to fit the visible rows, but it won't take into account the total number of rows in the grid. Therefore, if we want the height of the table to adjust based on the total number of rows in the grid, we need to use CSS to adjust. Once we set some overflow property of the container element to enable scrollbars when the content overflows the container, then this will also fix https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3756. We could also write some tests for it.

@curq @jgough do either one of you want to take this issue and https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3756?

**Comment by ananzh** [comment] 2023-04-04 16:24
Sweet! @curq I have assigned both issues to you.

**Comment by curq** [comment] 2023-04-06 17:20
@ananzh After further investigation, I have discovered that the root cause of the two issues is not the same. Regarding this issue, It looks like the state is being updated incorrectly or not being updated when needed. Additionally, I noticed that changing the order of rows in the options sidebar (asc/desc) does not work, and the height is sometimes not adjusted properly. I think we can also see that in the screenshot made by @jgough 

There is a weird behavior that state that is supposed to store value of height is never updated and the dynamic height adjustment works only when it is zero.
<img width="364" alt="image" src="https://user-images.githubusercontent.com/67782303/230448180-1ea4acdc-53b9-4c4a-b5ab-fca24013a326.png">
If we change the value of state [26] to 0, it fixes the layout and dynamic height adjusting works.
<img width="492" alt="image" src="https://user-images.githubusercontent.com/67782303/230448522-1f6247bc-09aa-4f23-8584-6949e32992e6.png">
When refreshing or opening the same page in a new tab it initializes this state as 0, so height changes correctly. I'm not sure, but it looks like this is the reason why bug appears only on initial load.

Do you have any ideas or suggestions on how to resolve this issue?

**Comment by ananzh** [comment] 2023-04-07 23:37
Yes, you are right. They are different root causes. 

https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3756 is caused by the table container's layout and overflow behavior. As I explained earlier, this can be fixed by modifying the CSS for the table container.

This issue is related to the EuiDataGrid component's handling of large amounts of data and pagination. The root cause lies within the resize not working/reacting on the initial load, resulting in the table displaying only a small area of the screen.

I was thinking about adding below 
```
.visTable {
  display: flex;
  flex-direction: column;
  flex: 1 0 0;
  overflow: auto;
}
```
Updating the CSS in this way also affects the way EuiDataGrid handles data within the table. With the modified CSS, the table container can now adjust its height based on the total number of rows in the grid (https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3756). This indirectly solves the pagination issue by displaying more rows in the table within the available space and having the table appear correctly paginated.

But I think your PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3797 solves the root cause of the pagination logic to adjust the number of rows displayed in the table. So if the user sets a high value for max rows per page, the pageSize will be limited to the total number of rows, ensuring that there's no excessive empty space.

@curq could you compare two approaches pros and cons? Maybe we should accept both, one for each issue. Then update your PR https://github.com/opensearch-project/OpenSearch-Dashboards/pull/3797 to fix both bugs. What do you think? Don't forget to update CHANGELOG.

**Comment by ananzh** [comment] 2023-04-10 20:01
@curq this is great. I approved both PRs and I will have another reviewer to take a look. Meanwhile, once the mentioned unit test PR, I will have you add/modify the unit test and submit a new PR for the test.

**Closed** 2023-04-12 17:39 UTC
Labels: bug, tableVis, CCI
