### ISSUE TITLE
[BUG] Data Table Sort no more persisted since 2.5.0

### ISSUE THREAD

**Issue by pmarjou** [opensearch-project/OpenSearch-Dashboards#3642] opened 2023-03-21 17:44 UTC
**Describe the bug**
Since version 2.5.0 the sort in the data table header is no more persisted at saved.

**To Reproduce**
1. Create a new Data Table Visualization
2. Select an index pattern
3. Add a Bucket Terms Aggregation
![image](https://user-images.githubusercontent.com/20339789/226689424-854ec486-77f3-4c15-8c43-ee2eed971371.png)
4. Sort "Asc" in the data table header
![image](https://user-images.githubusercontent.com/20339789/226689238-2bcda160-e4bd-4ff1-91e4-6c99e5dcfe40.png)
5. Save the visualization
6. Refresh the page in the browser
7. The sort is still "Desc"
![image](https://user-images.githubusercontent.com/20339789/226689786-3f5dc515-ac61-4474-8baa-615d25cae4d0.png)

**Expected behavior**
The sort should be persisted at visualization save.

**OpenSearch Version**
2.5.0

**Dashboards Version**
2.5.0

**Comment by abbyhu2000** [comment] 2023-03-21 21:35
Was able to reproduce the issue: 

Before release 2.5, the order can be changed by simply clicking the column title. And the sorting order will be persisted across refresh and also saved in the saved object.
<img width="1200" alt="Screen Shot 2023-03-21 at 2 24 15 PM" src="https://user-images.githubusercontent.com/43937633/226746377-1fdbcd97-f650-4f6a-8044-da37f5887648.png">


After release 2.5, the order can be changed by clicking the column title, and select either `sort desc` or `sort asc`. However, the sorting order will not be persisted across refresh, and it is also not saved in the saved object.
<img width="1200" alt="Screen Shot 2023-03-21 at 2 27 15 PM" src="https://user-images.githubusercontent.com/43937633/226746250-655a9f11-0fb3-4a67-bf0a-5bc82ecdd2c1.png">

**Comment by abbyhu2000** [comment] 2023-03-22 04:20
The regression was caused by this PR (replace table viz with react and data grid): https://github.com/opensearch-project/OpenSearch-Dashboards/pull/2863

**Comment by seanneumann** [comment] 2023-03-22 17:35
Let's get this fixed for 2.7.

**Comment by joshuarrrr** [comment] 2023-03-23 18:41
@abbyhu2000 Are you planning to fix this, or do we need to assign someone else?

**Comment by joshuarrrr** [comment] 2023-04-20 19:26
We ran out of time to make the updates after the blocking change was merged. So this will go in 2.8.0 instead.

**Comment by ananzh** [comment] 2023-05-31 20:16
This bug is fixed https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3650 which allows table vis to re-use uiState. I have verified that this bug is fixed after the above PR merged. 

Since https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3650 is released in 2.7, I will updated the tag back to 2.7 and close it.

**Closed by ananzh** 2023-05-31 20:16 UTC
Labels: bug, good first issue, tableVis, v2.7.0
