### ISSUE TITLE
[MD] Allow user to mark a data source as default and persist that in the metadata

### ISSUE THREAD

**Issue by BionIT** [opensearch-project/OpenSearch-Dashboards#6058] opened 2024-03-07 00:46 UTC
**Is your feature request related to a problem? Please describe.**

For index pattern management, we can mark an index pattern as default. That default index pattern is one shown up when the discover page renders. We should do the same for data sources

**Describe the solution you'd like**
We need to let users to mark a data source as default in the create and edit page, there should be one default data source.
The default property for the data source need to be persisted in the saved object

**Describe alternatives you've considered**
Have no default data source or the top one following alphabetic order sorted and decided at the front end

**Additional context**

**Comment by BionIT** [comment] 2024-03-07 00:47
@kgcreative Just created this issue, and please feel free to correct if anything is not correct

**Comment by zhyuanqi** [comment] 2024-03-12 21:33
Sure. Will work on this

**Comment by BionIT** [comment] 2024-03-13 15:46
Thanks @zhyuanqi for helping with this issue!

**Comment by bandinib-amzn** [comment] 2024-03-18 21:28
Duplicate of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5868. Please close this issue as well when you close this.

**Comment by zhyuanqi** [comment] 2024-03-27 17:06
Sure Let me close it

**Closed** 2024-03-27 17:08 UTC
Labels: enhancement, multiple datasource
