### ISSUE TITLE
Change blocklist to denylist to make consistency

### ISSUE THREAD

**Issue by ananzh** [opensearch-project/OpenSearch-Dashboards#1544] opened 2022-05-03 20:53 UTC
In [this OpenSearch PR](https://github.com/opensearch-project/OpenSearch/issues/1547):

```
Replace the old usages that having "blacklist/whitelist" in configurations with "denylist/allowlist", then create duplicate usages with the old terminology for backwards compatibility (including fallback logic to fallback to settings with the new name).
```

There are several references to blocklist in the core dashboards repo. One customer facing example is for the Graphite blocklist feature. To make consistency, we should replaced `blocklist` to `denylist`, including something related, for example `graphiteBlockedIPs`. 

This should not break anything. It is just for code consistency purpose.

**Comment by tmarkley** [comment] 2022-05-03 22:57
Is this a duplicate of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1319?

**Comment by joshuarrrr** [comment] 2022-05-03 23:32
I think the intent is that `blocklist` terminology should also be updated to `denylist`, in addition to the `blacklist` -> `denylist` change covered by #1319

**Comment by tmarkley** [comment] 2022-05-09 19:11
@joshuarrrr ahhh right, my brain was glossing over that when I first read it 😄

**Comment by kavilla** [comment] 2022-06-29 22:50
Removing `2.1` label due to code cutoff being today.

**Closed** 2022-08-04 22:33 UTC
Labels: bug, non-inclusive language, v2.2.0
