### ISSUE TITLE
[BUG] Unable to choose custom time for snapshot policies in Snapshot schedule

### ISSUE THREAD

**Issue by smowky** [opensearch-project/OpenSearch-Dashboards#8776] opened 2024-10-31 11:29 UTC
**Describe the bug**

Unable to choose snapshot time from dropdown menu (or type in). Whatever is chosen from the menu is discarded and time 20:00 is chosen instead.

**To Reproduce**
1. Go to snapshot management -> snapshot policies
2. Click on create policy
3. Scroll down to snapshot schedule
4. Make sure snapshot frequency is set to daily
5. From dropdown, pick a start time different from 20:00
6. Observe start time to see always 20:00 no matter what you choose
---
1. Go to snapshot management -> snapshot policies
2. Click on create policy
3. Scroll down to snapshot schedule
4. Make sure snapshot frequency is set to daily
5. Type in a start time different from 20:00
6. Observe start time to see always 20:00 no matter what you choose
---
1. Go to snapshot management -> snapshot policies
2. Click on create policy
3. Scroll down to snapshot schedule
4. Make sure snapshot frequency is set to weekly
5. Choose different day from Sunday
6. Observe no change in check boxes
---

**Expected behavior**
Expected to choose whatever time and day I prefer to make snapshot.

**OpenSearch Version**
VERSION 2.16 

**Dashboards Version**
VERSION 2.16
BUILD 7858
COMMIT 4b8826e7ffa6562825ca8aad676a8d89983c2d70

**Plugins**
|	ID	| Status|
--- | ---|
| core:opensearch@2.16.0	| OpenSearch is available |
|core:savedObjects@2.16.0 |SavedObjects service has completed migrations and is available |
|plugin:advancedSettings@2.16.0 | All dependencies are available |
|plugin:charts@2.16.0 | All dependencies are available |
|plugin:bfetch@2.16.0 | All dependencies are available|
|plugin:contentManagement@2.16.0 | All dependencies are available |
|plugin:dataExplorer@2.16.0 | All dependencies are available |
|plugin:devTools@2.16.0 | All dependencies are available |
|plugin:discover@2.16.0 | All dependencies are available |
|plugin:embeddable@2.16.0 | All dependencies are available |
|plugin:expressions@2.16.0 |All dependencies are available |
|plugin:indexPatternManagement@2.16.0 | All dependencies are available |
|plugin:inspector@2.16.0 | All dependencies are available |
|plugin:legacyExport@2.16.0 | All dependencies are available |
|plugin:management@2.16.0 |All dependencies are available |
|plugin:managementOverview@2.16.0 | All dependencies are available |
|plugin:navigation@2.16.0 | All dependencies are available |
| plugin:opensearchDashboardsOverview@2.16.0 |All dependencies are available |
|plugin:opensearchDashboardsReact@2.16.0 | All dependencies are available |
|plugin:opensearchDashboardsUsageCollection@2.16.0 |All dependencies are available |
|plugin:opensearchDashboardsUtils@2.16.0 | All dependencies are available|
|plugin:opensearchUiShared@2.16.0 | All dependencies are available |
|plugin:savedObjects@2.16.0 | All dependencies are available |
|plugin:savedObjectsManagement@2.16.0 |  All dependencies are available |
|plugin:share@2.16.0 | All dependencies are available |
|plugin:uiActions@2.16.0 | All dependencies are available |
|plugin:urlForwarding@2.16.0 | All dependencies are available |
|plugin:visDefaultEditor@2.16.0 | All dependencies are available |
|plugin:visualizations@2.16.0 |  All dependencies are available |
|plugin:visualize@2.16.0 | All dependencies are available |
|plugin:ganttChartDashboards@2.16.0 | All dependencies are available |
|plugin:notificationsDashboards@2.16.0 | All dependencies are available |
|plugin:apmOss@2.16.0 | All dependencies are available |
|plugin:console@2.16.0 | All dependencies are available |
|plugin:dashboard@2.16.0 | All dependencies are available |
|plugin:data@2.16.0 | All dependencies are available |
|plugin:dataSourceManagement@2.16.0 | All dependencies are available |
|plugin:home@2.16.0 | All dependencies are available |
|plugin:inputControlVis@2.16.0 | All dependencies are available |
|plugin:mapsLegacy@2.16.0 | All dependencies are available |
|plugin:opensearchDashboardsLegacy@2.16.0 | All dependencies are available |
|plugin:queryEnhancements@2.16.0 | All dependencies are available |
|plugin:regionMap@2.16.0 | All dependencies are available |
|plugin:tileMap@2.16.0 | All dependencies are available |
|plugin:usageCollection@2.16.0 | All dependencies are available |
|plugin:visAugmenter@2.16.0 | All dependencies are available |
|plugin:visBuilder@2.16.0|All dependencies are available|
|plugin:visTypeMarkdown@2.16.0|All dependencies are available|
|plugin:visTypeMetric@2.16.0|All dependencies are available|
|plugin:visTypeTable@2.16.0|All dependencies are available|
|plugin:visTypeTagcloud@2.16.0|All dependencies are available|
|plugin:visTypeTimeline@2.16.0|All dependencies are available|
|plugin:visTypeTimeseries@2.16.0|All dependencies are available|
|plugin:visTypeVega@2.16.0|All dependencies are available|
|plugin:visTypeVislib@2.16.0|All dependencies are available|
|plugin:alertingDashboards@2.16.0|All dependencies are available|
|plugin:customImportMapDashboards@2.16.0|All dependencies are available|
|plugin:indexManagementDashboards@2.16.0|All dependencies are available|
|plugin:reportsDashboards@2.16.0|All dependencies are available|

**Screenshots**
![Untitled](https://github.com/user-attachments/assets/9438e391-c40e-46fd-8ece-a342b45afe61)

**Host/Environment (please complete the following information):**
- docker 2.16.0 image
- Firefox 131.0.3 / Chromium 130.0

**Additional context**

Other that than snapshot policies from web UI does works as expected, even possible to create snapshot policy when I'll keep default 20:00 on daily snapshot.

**Comment by andrross** [comment] 2024-11-18 17:29
[[Catch All Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta), [3](https://github.com/andrross/), [4](https://github.com/krisfreedain), [5](https://github.com/amistrn)]

Looks like a duplicate of #8775. Please reopen if you think this is incorrect.

**Closed by andrross** 2024-11-18 17:29 UTC
Labels: bug, untriaged
