### ISSUE TITLE
[BUG] 2.13.0 Discover - using "refresh every" closes panel instantly

### ISSUE THREAD

**Issue by sandervandegeijn** [opensearch-project/OpenSearch-Dashboards#6490] opened 2024-04-16 18:58 UTC
**Describe the bug**

https://github.com/opensearch-project/OpenSearch-Dashboards/assets/2643715/6203ceda-7d30-48c5-964a-7e1d1a1e3835

**Expected behavior**
I'm able to type whatever value I want and press start

**OpenSearch Version**
2.13.0

**Dashboards Version**
2.13.0

**Plugins**
Default docker container

**Screenshots**

^^

**Host/Environment (please complete the following information):**
FIrefox 124.0.2 (64-bit)

**Additional context**

N/A

**Comment by kavilla** [comment] 2024-04-23 17:29
@sandervandegeijn thanks for opening, we were able to re-produce it.

**Comment by sandervandegeijn** [comment] 2024-04-23 21:54
Fantastic, thank you!

**Comment by ananzh** [comment] 2024-06-21 16:23
This is resolved in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/6167
The problem is double render causing unmount.

**Comment by sandervandegeijn** [comment] 2024-06-21 16:24
Fantastic - thanks!

**Closed by ananzh** 2024-06-21 16:23 UTC
Labels: bug, discover
