### ISSUE TITLE
[BUG] 'Add data' links are broken

### ISSUE THREAD

**Issue by ahopp** [opensearch-project/OpenSearch-Dashboards#373] opened 2021-05-25 04:28 UTC
**Describe the bug**
If you try to add data and click the available links for 'Learn more' or 'See the Quick Start' you will ingress into a 404'd page in opensearch.org. 

**To Reproduce**
1. Go to 'Add data'
2. Click on any listed data source
3. Click 'Learn more' OR 'See the Quick Start'
4. See 404 page

Some examples;
https://www.opensearch.org/guide/en/beats/metricbeat/main/metricbeat-module-azure.html
https://www.opensearch.org/guide/en/beats/filebeat/main/filebeat-module-checkpoint.html
https://www.opensearch.org/guide/en/beats/metricbeat/main/metricbeat-installation-configuration.html
https://www.opensearch.org/guide/en/beats/filebeat/main/filebeat-installation-configuration.html

**Expected behavior**
We would expect the pages to not 404. 

**OpenSearch Version**
Current v1.0.0 (beta)

**Dashboards Version**
Current v1.0.0 (beta)

**Plugins**
Not relevant. 

**Screenshots**
Example Source 1;
![Source](https://user-images.githubusercontent.com/9532728/119438507-377e1d80-bcd5-11eb-8fbc-2c47fe4d8a06.png)

Example Source 2;
![image](https://user-images.githubusercontent.com/9532728/119438847-f9352e00-bcd5-11eb-8f75-e00c86901acb.png)

Example Destination (404);
![Destination](https://user-images.githubusercontent.com/9532728/119438543-4ebd0b00-bcd5-11eb-8e42-62ef18b1285e.png)

**Comment by kavilla** [comment] 2021-05-30 08:52
Thanks @ahopp, I would consider this a sub-issue of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/335.

But will keep this issue open because this helps to have specific issues.

Thanks!

**Comment by kavilla** [comment] 2021-07-19 20:07
Will close this as technically a duplicate of this issue #647, right now we remove the ability to get these docs within this application but you can directly go these by typing the route. We need to remove the routes from the router. Will use #335 for final URLs.

**Closed by kavilla** 2021-07-19 20:07 UTC
Labels: bug
