### ISSUE TITLE
[BUG] In Data Table visualisations the Update button is no longer locked to the bottom of the screen

### ISSUE THREAD

**Issue by jgough** [opensearch-project/OpenSearch-Dashboards#3756] opened 2023-03-31 13:21 UTC
**Describe the bug**

When creating a Data Table visualisation, setting the _Max rows per page_ to a high value can result in the _Update_ button appearing a long way down the page

**To Reproduce**
1. Create a Data Table visualisation, or go to [this playground link](https://playground.opensearch.org/app/visualize#/create?type=table&savedSearchId=571aaf70-4c88-11e8-b3d7-01146121b73d&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-1y,to:now))&_a=(filters:!(),linked:!t,query:(language:kuery,query:''),uiState:(),vis:(aggs:!((enabled:!t,id:'1',params:(),schema:metric,type:count),(enabled:!t,id:'2',params:(field:AvgTicketPrice,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!f,otherBucketLabel:Other,size:50),schema:bucket,type:terms),(enabled:!t,id:'3',params:(field:dayOfWeek,missingBucket:!f,missingBucketLabel:Missing,order:desc,orderBy:'1',otherBucket:!f,otherBucketLabel:Other,size:5),schema:bucket,type:terms)),params:(perPage:10,percentageCol:'',row:!t,showMetricsAtAllLevels:!f,showPartialRows:!f,showTotal:!f,totalFunc:sum),title:'',type:table)))
2. Note that the _Update_ button appears locked at the bottom right of the screen, in line with other visualisations
![image](https://user-images.githubusercontent.com/968442/229099127-5dd19e46-48cd-4350-9c74-882d8488f7d4.png)
3. Click Options on the side bar and change _Max rows per page_ to 1000.  Click _Update_
4. Note that the _Update_ button moves a very long way down the sceen.

**Expected behavior**
The Update button should always be visible at the bottom right of the screen, in line with other visualisations.  This used to be the case on Data Table visualisations but I think this has changed in a recent update.

**OpenSearch Version**
2.6.0

**Dashboards Version**
2.6.0

**Screenshots**

(Shown with a value of 100 for Max rows per page here to avoid a massive screenshot, but setting this value to 1000 illustrates the issue more clearly if you want to try)
![image](https://user-images.githubusercontent.com/968442/229100142-38388903-6948-4df3-9c45-a51f23dcc5d4.png)

**Host/Environment (please complete the following information):**
Reproduced in Edge 111.0.1661.54 and Firefox 102.9.0esr

**Comment by joshuarrrr** [comment] 2023-03-31 23:43
Yeah, likely the same root cause as https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3737, so it probably makes sense to investigate them together. But thanks for opening as separate issues - it helps us stay better organized and make sure we have the right exit criteria.

**Comment by curq** [comment] 2023-04-01 15:45
I took a look at this bug and I think I found the cause. I made a quick sketch to show the structure of the flexboxes to better understand the problem. The largest container (yellow) hold the table, slider and the sidebar(black). The blue container takes all free space in the sidebar container. So the UPDATE button always at the bottom.
<img width="1291" alt="sketch" src="https://user-images.githubusercontent.com/67782303/229298390-8a3307be-dacf-4921-b5ba-805ed1c636eb.png">
When the table is large the sidebar grows alongside with table component and the blue container takes the free space so the Update button goes to very bottom.
<img width="1293" alt="Screenshot 2023-04-01 at 20 57 09" src="https://user-images.githubusercontent.com/67782303/229298755-f08deb57-28f3-41f8-939b-71d6ed14ab19.png">
Also in provided case the value of max rows is 100, while the number of fields is 50, so the the component that renders the table adjust its height to fit 100 rows, but because we have 50 results half of the component is empty. With the increase of its size, the sidebar size also increased where the options flex item (blue container) takes all free space. As a result the UPDATE button moves to the very bottom of the page.

@joshuarrrr What are you thoughts about it? What is the best way to approach the problem?

**Comment by ananzh** [comment] 2023-04-04 15:37
@curq and @jgough I have provided my thoughts [here](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3737#issuecomment-1496194182).

If you guys feel interested and would like to help, I could assign you these two issues.

**Comment by ananzh** [comment] 2023-04-04 16:25
Based on this comment [here](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3737#issuecomment-1496217925), I have assigned this issue to @curq and thank you for helping.

**Comment by curq** [comment] 2023-04-06 17:22
@ananzh I have solved the problem that was causing the displacement of the UPDATE button far below the table, but I have found that the root cause of the two issues is not the same. I have explained more about it in the [comments](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3737#issuecomment-1499383953) of the second issue

**Comment by ananzh** [comment] 2023-04-07 23:39
@curq add my comment here https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3737#issuecomment-1500723388

**Closed** 2023-04-14 20:32 UTC
Labels: bug, tableVis, v2.7.0, CCI
