### ISSUE TITLE
[BUG] Context page in discover does not highlight the document row for which we see the surrounding docs

### ISSUE THREAD

**Issue by amsiglan** [opensearch-project/OpenSearch-Dashboards#6048] opened 2024-03-05 23:41 UTC
**Describe the bug**
When viewing surrounding documents the main document providing the context should be highlighted.

**To Reproduce**
1. Go to the discover page
2. View documents for any index with a timestamp
3. Expand one of the docs from the list and click on `View surrounding logs` which would open a new tab and show a list of documents surrounding that particular document.

**Expected behavior**
In the new tab, the document for which we are viewing surrounding docs should have been highlighted.

**OpenSearch Version**
2.11

**Dashboards Version**
2.11

**Screenshots**
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/114732919/5edbb265-71d2-4fa6-9fa4-f2d702598c96)

![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/114732919/1e9cd4f2-5c24-4bc5-80b1-007e37b0a73e)

**Comment by ananzh** [comment] 2024-06-21 16:25
This is duplicate of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/6457 and it is resolved.
Close the issue.

**Closed by ananzh** 2024-06-21 16:25 UTC
Labels: bug, discover
