### ISSUE TITLE
[BUG] Problem with narrowing the list of records if the number of hits increases

### ISSUE THREAD

**Issue by kinseii** [opensearch-project/OpenSearch-Dashboards#5845] opened 2024-02-08 18:01 UTC
**Describe the bug**

We observe the following problem: if the search contains a small number of hits, e.g. 1-2 pcs., the size of the window with the list of records does not change when the filter is expanded (e.g. the time interval is increased). Thus, the search is performed inside the window with previous smaller sizes, which is extremely inconvenient.

**To Reproduce**
1. Create a filter so that you only have 1-2 records.
2. Then expand the time interval or exclude some kind of filter to have more hits.

The size of the window with the list of records will remain the same and you will be forced to search inside this small window.

**Expected behavior**
The window size should expand accordingly to the selected maximum number of records on one sheet.

**OpenSearch Version**
2.11.1

**Dashboards Version**
2.11.1

**Plugins**
```
opensearch-alerting                  2.11.1.0
opensearch-anomaly-detection         2.11.1.0
opensearch-asynchronous-search       2.11.1.0
opensearch-cross-cluster-replication 2.11.1.0
opensearch-custom-codecs             2.11.1.0
opensearch-geospatial                2.11.1.0
opensearch-index-management          2.11.1.0
opensearch-job-scheduler             2.11.1.0
opensearch-knn                       2.11.1.0
opensearch-ml                        2.11.1.0
opensearch-neural-search             2.11.1.0
opensearch-notifications             2.11.1.0
opensearch-notifications-core        2.11.1.0
opensearch-observability             2.11.1.0
opensearch-performance-analyzer      2.11.1.0
opensearch-reports-scheduler         2.11.1.0
opensearch-security                  2.11.1.0
opensearch-security-analytics        2.11.1.0
opensearch-sql                       2.11.1.0
repository-azure                     2.11.1
repository-s3                        2.11.1
```

**Screenshots**
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/74458264/43d541c9-5e98-493f-93e8-e839e23f6959)
![image](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/74458264/cc66592f-7e47-4547-8636-7aae64e97444)

**Host/Environment (please complete the following information):**
- Operational systems on workstations: tested on Linux Kubuntu 22.04 and macOS Sonoma 14.1.1
- Browser and version on workstations: Chrome Version 121.0.6167.139 (Official Build) (64-bit)
- OpenSearch Cluster: v.2.11.1 on AKS v.1.27.7 with Ubuntu 22.04 nodes
- OpenSearch Cluster Dashboards: v.2.11.1 on AKS v.1.27.7 with Ubuntu 22.04 nodes

**Comment by ananzh** [comment] 2024-02-09 21:21
@kinseii, I think the issue you raised here is duplicate of [#5659](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5659),  [#5440](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5440) and
[#5678](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5678).

Check my comments in [#5659](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5659) and [#5678](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5678), where I uploaded videos for how we resolve the problem. We fixed this in 2.12 which will soon be released in public. You could now play with our main or 2.12 branch. 

If you agree with me, could we just close this issue and follow on the other two?

**Closed** 2024-02-13 19:02 UTC
Labels: bug, duplicate, discover, v2.12.0
