### ISSUE TITLE
SigV4 supports different service name and other service's test connection

### ISSUE THREAD

**Issue by Flyingliuhub** [opensearch-project/OpenSearch-Dashboards#3718] opened 2023-03-28 18:27 UTC
**Is your feature request related to a problem? Please describe.**

The current SigV4 didn't support OpenSearch serverless's service type, it should give customer option to choose which service name they would like to connect. 

There is different test connection for OpenSearch serverless, it is different than other service, probably need to check different api, like _cat/indices for the test connection of SigV4. 

**Describe the solution you'd like**

Use SigV4 to connect OpenSearch serverless, provide customer option to choose `service name`, which can handle all kind of service connection

May use _cat/indices for test connection if customer want to use SigV4 to connect to OpenSearch serverless.

**Describe alternatives you've considered**

N/A

**Additional context**

SigV4 test connect for OpenSearch serverless
![image](https://user-images.githubusercontent.com/33105471/228332404-952731ce-d39f-4946-bee0-4a7566eec614.png)

Service name error

![image](https://user-images.githubusercontent.com/33105471/228332896-3c1dfcc0-7d07-4bb3-a292-dc80df370b55.png)

**Comment by zhongnansu** [comment] 2023-04-03 20:55
@Flyingliuhub what are the candidate values for `service name`? 
- `es` => AWS OpenSearch
- `serverless` => OpenSearch serverless

Anything else?

**Comment by zhongnansu** [comment] 2023-04-17 16:12
note: duplicate of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3623

**Comment by zhongnansu** [comment] 2023-06-15 21:45
closing as the feature is added

**Closed by zhongnansu** 2023-06-15 21:45 UTC
Labels: duplicate, enhancement, multiple datasource
