### ISSUE TITLE
Time field is not getting saved in kibana view. It is showing earlier selected timefield.

### ISSUE THREAD

**Issue by rakhinarveka1** [opensearch-project/OpenSearch-Dashboards#4748] opened 2023-08-16 06:33 UTC
**Describe the bug**

**To Reproduce**
1. Go to Discover, Created view with timefield 'Last 30 days'
2. Save kibana view with name 'Last 30 days'.
3. while opened the same view again , It does show timefield selected  at the time of kibana view creation. here i.e. Last 30 days 

**Expected behavior**
If we are opening specific kibana view, it should show the selected Timefield when kibana view created. But it shows earlier timefield selected on screen irrespective of whatever view selected.

**OpenSearch Version**
Opensearch dashboard 1.3

**Screenshots**

View created as below,
<img width="947" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/111862494/72a83fa9-f381-4747-8df6-a03c4f3769a2">

but when reopened again, not showing same timefield.

<img width="956" alt="image" src="https://github.com/opensearch-project/OpenSearch-Dashboards/assets/111862494/af95336b-2bf5-4a2d-8a06-3fe7bc6a6577">

**Comment by zhongnansu** [comment] 2023-08-22 22:43
@rakhinarveka1 I couldn't reproduce this issue, but I suggest 2 things for you to take another look.
1. could you update to the latest version of Dashboards and see if there'e still issue?
2. make sure you save the current discover view as a "search" after selecting the time range

**Comment by ashwin-pc** [comment] 2023-08-24 12:04
@rakhinarveka1 the time field is not a part of the saved view. When you save a view the columns selected, their sort order and the index pattern selected is saved. The query used, the timerange are part of the global state and thus is persisted across apps. e.g. when you switch between Discover and Dashboard, the time range stays the same. I dont think there is a plan to update this behavior right now.

If you want to save the timerange, I suggest using the saved query option. This saves the query and timerange and is accessible using the save icon next to the search bar.

Closing this for now, feel free to reopen if this does not address your issue

**Closed by ashwin-pc** 2023-08-24 12:04 UTC
Labels: bug, needs more info
