### ISSUE TITLE
[BUG] Red Panel in the discover results panel

### ISSUE THREAD

**Issue by dewsingh** [opensearch-project/OpenSearch-Dashboards#8316] opened 2024-09-24 10:34 UTC
**Describe the bug**

With the latest Chrome 129 browser, the dashboards discover results pane displays a red panel in place of the result values when the results panel is expanded.

**To Reproduce**
1. Login into dashboards GUI. 
2. Go to Discover UI
3. Select an index and then Scroll down to the results pane. Initially the results are displayed as expected.
![Discover_home](https://github.com/user-attachments/assets/03ff2b99-5472-44c3-abee-3d55bd9798e3)
4. Expand the results. A red panel is displayed now.
![Discover_home_expand_result](https://github.com/user-attachments/assets/6432644d-a04f-459b-8c35-933b1577f444)

**Expected behavior**
The results panel should expand to show details of the document.

**OpenSearch Version**
2.12.0

**Dashboards Version**
2.12.0.0

**Plugins**

SecurityDashboards, ReportDashboards

**Host/Environment (please complete the following information):**
 - Google Chrome Version 129.0.6668.59
 
**Additional context**

This issue is not observed in the older Chrome browser Version 128.

**Comment by ihtkas** [comment] 2024-09-24 14:45
I am also facing the same issue. The issue is observed in Chrome and Arc browsers.

**Comment by sahil-rathi** [comment] 2024-09-24 14:46
Facing the same issue whenever any log is expanded in legacy mode.

**Comment by DougllasLima** [comment] 2024-09-24 16:18
I am experiencing the same issue with this version of Chrome: Version 129.0.6668.59 (Official Build) (64-bit). The issue has not been observed in Microsoft Edge.

**Comment by Swiddis** [comment] 2024-09-24 17:45
Duplicate: #8250

**Comment by TanweerulHaque** [comment] 2024-09-25 06:28
I am also observing the same issue in brave browser. 
CSS: `.eui-xScrollWithShadows`, the properties `-webkit-mask-image` and `mask-image` are set with red colors. Unchecking these properties removes the red screen.

**Comment by shachar-karry** [comment] 2024-09-26 10:04
I use managed Opensearch by AWS.
After upgrading to Chrome 129 this begun.

I updated OpenSearch version to 2.15 (latest on AWS) and seems the problem is solved with the fix in: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/8277

Thanks 🙏

**Comment by SricharanSundar** [comment] 2024-09-27 05:59
Hi all,
I'm using Chrome Version 129.0.6668.71 (Official Build) (64-bit).
The OpenSearch is working fine for me. Using(OpenSearch 2.13 managed service)

**Comment by javad87** [comment] 2024-09-27 08:20
I encountered this issue as well on Chrome version: Chrome is up to date Version 129.0.6668.71 (Official Build) (64-bit)
Opensearch: v 2.12.0 deployed by docker on AWS EC2 machines.

![image](https://github.com/user-attachments/assets/c5460139-d0c5-4b40-9083-553282b26715)

**Comment by george-kirkman** [comment] 2024-09-27 10:39
I also encountered this issue on Chrome and Arc
- OpenSearch v 2.11.0
- Arc Version 1.61.0 (53949) (Chromium Engine Version 129.0.6668.59)

**Comment by MaxStlbv** [comment] 2024-09-27 13:36
hey! 
the same problem 
OpenSearch - v 2.11.0
GH - Version 129.0.6668.71

**Comment by prasadjella** [comment] 2024-09-30 07:45
I'm facing same issue in Microsoft edge browser Version 129.0.2792.65 (Official build) (64-bit)

**Comment by M-Porter** [comment] 2024-09-30 21:11
I hate doing a "me as well" comment, but given how little traction this has over the last week... its happening to me as well.

**Comment by JViggiani** [comment] 2024-10-04 11:19
Same issue

**Comment by joaopfcruz** [comment] 2024-10-07 11:14
Not sure if it helps (or even if this is a long-term fix) but today I faced this red panel for the first time. After I deleted browser cookies and cache the results panel suddenly got back to normal.

Opensearch: 2.15 (AWS-managed)
Chrome:  129.0.6668.71

**Comment by dblock** [comment] 2024-10-14 16:07
Closing as duplicate, please add any comments to #8250

**Comment by dblock** [comment] 2024-10-14 16:07
[Catch All Triage - [1](https://github.com/dblock), [2](https://github.com/refa), [3](https://github.com/andrross), [4](https://github.com/krisfreedain)]

**Closed by dblock** 2024-10-14 16:07 UTC
Labels: bug, untriaged
