### ISSUE TITLE
[Proposal] Consolidated Dev Tools

### ISSUE THREAD

**Issue by brijos** [opensearch-project/OpenSearch-Dashboards#3033] opened 2022-12-05 22:59 UTC
**Is your feature request related to a problem? Please describe.**

There are multiple ways to query OpenSearch within OpenSearch (e.g. Dev Tools, Query Workbench). To make it less complicated and drive adoption for a variety of querying methods offered in OpenSearch, we want to build a central location to make querying for users in OpenSearch easy. 

**Describe the solution you'd like**

To have one querying workbench experience where users can query OpenSearch in the language that they are most familiar with.

* When troubleshooting an OpenSearch cluster or data within the cluster, an admin wants a central place to quickly troubleshoot and develop queries using languages they are familiar with, so that they can quickly find out what is going on with their system.
* When learning about a new query interface, users will want to use a search and results interface which feels similar to other query interfaces in the tool, so that they don’t have to learn a new way of doing things.
* When revisiting a query interface, an user wants to select/save x previously run queries, so that they don’t waste their time recalling popular queries.
* When someone from compliance wants to see what queries have been run on OpenSearch, a user of OpenSearch wants to be able to show what queries have been run.
* When coming upon schema structures which are not familiar, an user will want to explore the possible data structures, so that they can build the right query with confidence.
* When constructing new queries, a novice user will want quick access to documentation/examples/help on how to construct queries, so that they can learn as they go and feel confident in the project.
* When constructing a query incorrectly, all users want to be told why the query isn’t executing, so that they can fix their mistakes and move on (e.g. EXPLAIN)
* When constructing queries, performance conscious users and cluster administrators want to understand how the query could be written more efficiently, so that they can avoid taking up critical cluster resources.

**Describe alternatives you've considered**

Leaving the different ways to query OpenSearch as is.

**Additional context**

Mockups to come soon.

**Comment by kavilla** [comment] 2022-12-06 07:29
Is the proposal removing the console plugin in favor of query workbench? Or enabling the console plugin to utilize SQL? Or nothing to do with the query workbench plugin.

 Right now I would say the dev tools really lets you hit the REST APIs of OpenSearch and OpenSearch Dashboards and copy those as a curl if wanted.

**Comment by brijos** [comment] 2022-12-08 14:14
Exactly what David said. This is a consolidation effort to made the various tools more findable and usable.

**Comment by dtaivpp** [comment] 2022-12-09 15:42
I think that would be great (generating the postman collections from spec that is). I've though this would be great as well. 

We do have the [opensearch cli](https://opensearch.org/docs/1.0/clients/cli/) which I think was supposed to serve a similar function but it hasn't seen the adoption I'd like. I feel like everyone is really familiar with postman though so that would probably get a ton of traction. 

The thing I really like about our web interface for doing this is the auto completion and how it can work kinda like a notebook.

**Comment by dcarbone** [comment] 2022-12-09 16:35
the opensearch cli tool works very well, but from personal experience it has some shortcomings:

1. can easily list profiles by name, but cannot view actual profile config
2. cannot edit a profile
3. possible paths in `curl` command are not hintable
   * this could potentially be helped with the availability of an openapi-like schema file that could be loaded on-demand to produce autocomplete hints.
5. cli tool is not readily available in any repos, including the rpm repo maintained for the actual opensearch service itself

those are just the ones i've run into recently.  i do appreciate its existence, however :)

**Comment by seraphjiang** [comment] 2023-01-26 17:28
## Dev Tools
As a OpenSearch Developer, I'd like to keep all existing Dev Tool functionality, that is primary tool people use to learn and debug OpenSearch Query. I'm not sure if people has need to learn other query language.

As a developer, when I learn OpenSearch API, DSL, dev tool is my best bet. Other query tool or query lanauge are nice to help.

Learn how to use SQL/PPL might only use for query some data, it doesn't help to learn and debug OpenSearch API. 
How many OpenSearch user will use SQL/PPL to run POST/PUT/DELETE api , which are important to ingest/manage data. 

Admin persona might represent some usage, and scenario, but could not cover major use case for me to make decision to have one centralized tool to replace existing tools. Love to hear more input.


## Observability (Log Analytic)case 
I saw there is overlap between `Discovery app` and `Workbench` , but i'd like to have more comprehensive side by side functionality comparison between these two to understand their existing usage, and what are required if we do want to merge, what could be removed.

## Search Relevance
The need and use cases for Search are very different compare to Log Analytic. @macohen might provide more input.

@AMoo-Miki @seanneumann  @anirudha @elfisher @ahopp @kgcreative @zengyan-amazon @macohen @xinlamzn  @dblock

**Comment by brijos** [comment] 2023-02-22 12:37
Made updates to extend the user stories based on users and Admins. The initial focus was admins, but power users will also benefit from having a single location to query from.

**Comment by macohen** [comment] 2023-03-14 15:10
Can we look at any consolidation from the perspective of the user? A search relevance engineer is going to want a different set of tools than someone monitoring systems and applications, but there is overlap in the usefulness of each tool. I can imagine a set of plugins that are great for observability only, some that are great for search and some that work for both.

**Comment by vagimeli** [comment] 2023-09-13 17:57
See PRs:
- https://github.com/opensearch-project/documentation-website/pull/4874

Doc team creates the Dev Tools content when doc issues are created. Please prioritize the topics and add me to the doc issues as the point of contact.

**Comment by ashwin-pc** [comment] 2023-09-14 01:14
Just want to add here that we are confusing `devtools` with `console`. Devtools is simply a wrapper plugin that allows a plugin developer to register any developer tool under it. Right now only the console plugin makes use of this registration, but was built with the intention that more plugins would do the same. The easiest approach here might just be to have all the other dev tools related apps like search relavance and query workbench to do the same. 

here is where the console application registers itself as a dev tool: https://github.com/opensearch-project/OpenSearch-Dashboards/blob/main/src/plugins/console/public/plugin.ts#L58C1-L87

**Comment by kgcreative** [comment] 2023-09-14 17:27
Yes -- i think the idea here is not to combine all these tools, but rather to make them all available as tabs in devtools. Devtools I think was intended to house all the different tools that devs and folks working more specialized advanced tasks could need. To me, Devtools housing Console | Query Workbench | Search Comparison makes sense, as those are intended to help developers in their day to day. This is orthogonal to Log Explorer + Discover being merged into Data Explorer. I wouldn't equate data explorer with dev tools. (If that makes sense)

**Comment by macohen** [comment] 2023-09-14 17:43
For Search Relevance, the goal is to expand this beyond what I now think I understand are developer tools. Thanks @ashwin-pc. The audience may be non-developers rating results, interest in search analytics, as well as relevance tuning, A/B testing, more. Ideas in the space need to evolve, but I would not want to move the comparison tool in and out of dev tools.

**Comment by macrakis** [comment] 2023-09-14 19:49
Agreed with Mark. Many business users and product managers who don’t write queries will want insight into the performance of search. Search Comparison is just the first (small!) step in that direction.

Cf. Aparna’s different personas.

From: Mark Cohen ***@***.***>
Reply-To: opensearch-project/OpenSearch-Dashboards ***@***.***>
Date: Thursday, September 14, 2023 at 13:44
To: opensearch-project/OpenSearch-Dashboards ***@***.***>
Cc: Stavros Macrakis ***@***.***>, Mention ***@***.***>
Subject: Re: [opensearch-project/OpenSearch-Dashboards] [Proposal] Consolidated Dev Tools (Issue #3033)
Resent-From: ***@***.***>


For Search Relevance, the goal is to expand this beyond what I now think I understand are developer tools. Thanks @ashwin-pc<https://github.com/ashwin-pc>. The audience may be non-developers rating results, interest in search analytics, as well as relevance tuning, A/B testing, more. Ideas in the space need to evolve, but I would not want to move the comparison tool in and out of dev tools.

**Comment by kgcreative** [comment] 2023-09-14 21:29
I'm ok with Search Comparison staying together with other search relevance tools, as this will quickly outgrow the devtools context

**Comment by AMoo-Miki** [comment] 2023-10-11 19:37
As a non-tech user, complicated interfaces with a ton of tabs and knobs confuse me; in fact, too many options are entry barriers for people like me. `Discover` is that uncomplicated interface for the likes of me to just get the data we need; I am with @seraphjiang on that.

Plugins, on the other hand, are free to create specialized interfaces or much more complex multi-usecase interfaces, even duplicating parts of existing OSD functionality.`Discover` cannot afford to do that because it would just alienate everyone who needs simple easy-to-use interfaces. 

With the `Dev Tools`, like @ashwin-pc said, plugins can choose to add themselves there and the `Console`, being targeted at technical folks, can enrich itself with richer UX but complicating `Console` with numerous querying techniques will need a spectacular UX to not be a pain to use.

**Comment by kgcreative** [comment] 2023-10-11 20:39
I propose we close this issue for now.

**Closed** 2023-10-12 00:28 UTC
Labels: enhancement, proposal, console
