### ISSUE TITLE
[BUG] Close button appears outside the chrome of the sidebar

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch-Dashboards#1443] opened 2022-04-11 20:16 UTC
**Describe the bug**
On the collapsibleNav in OpenSearch Dashboards, there is a close button, and the button is floating outside the bounds of the nav.  It seems like there is plenty of space to include the button in the nav itself.

**To Reproduce**
1. Start opensearch-dashboards
2. Sign in
3. Look at the side nav menu 
![image](https://user-images.githubusercontent.com/2754967/162823951-f420cd74-94ce-4c7a-a658-3020904eb6e5.png)

**Expected behavior**
The button should be within the bounds of the nav bar

~**OpenSearch Version**~

**Dashboards Version**
v2.0.0, commit `:db7cb6d115e` 

**Host/Environment:**
 - OS: Windows 
 - Browser and version: Chrome v100

**Comment by kgcreative** [comment] 2022-04-11 20:33
This is intended behavior that is part of folding the latest EUI in. We will revise this in a future update. In the meantime, we should align on using the `menuLeft` and `menuRight` icons to open/close the side menu to better align with the correct behavior. For now, the button being outside the container is not unintended behavior.

<img width="110" alt="Screen Shot 2022-04-11 at 1 30 41 PM" src="https://user-images.githubusercontent.com/3443142/162826828-eca41797-e11e-4e01-948b-e1d6cef17907.png"><img width="110" alt="Screen Shot 2022-04-11 at 1 30 57 PM" src="https://user-images.githubusercontent.com/3443142/162826822-95a17720-7420-4a4b-9628-48c2c0841305.png">

**Comment by kavilla** [comment] 2022-04-11 20:41
+1 @kgcreative

Yeah I agree! This is expected functionality form EUI. Based on this comment: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/1370#issuecomment-1080949461 should close this as duplicate for: https://github.com/opensearch-project/OpenSearch-Dashboards/issues/569

**Comment by seanneumann** [comment] 2022-04-11 20:57
@kavilla please do. Thanks.

**Closed** 2022-04-11 20:58 UTC
Labels: bug, duplicate, v2.0.0
