### ISSUE TITLE
Discover Page : Multiple documents opening at same time

### ISSUE THREAD

**Issue by gupta-mayank** [opensearch-project/OpenSearch-Dashboards#5602] opened 2023-12-13 03:45 UTC
**Problem Statement:**

In earlier version of OpenSearch Dashboards, you can expand multiple document at the same time, now with new implementation, it is opening one doc in flyout at a time. 

**Proposed Solution**
Enabling multiple doc expand in search result for better triaging, we use mainly for logs and hence correlation with one log to another is important for training our issues.

**Alternatives Considered**
Select the columns which are of interest and scroll through them rather than opening complete docs.

**Comment by ashwin-pc** [comment] 2023-12-15 08:05
Closing this as a duplicate of #5555

**Closed by ashwin-pc** 2023-12-15 08:05 UTC
Labels: enhancement, untriaged
