### ISSUE TITLE
Scrolling issue on New discover search

### ISSUE THREAD

**Issue by MohanKNVMNEKTAN** [opensearch-project/OpenSearch-Dashboards#5149] opened 2023-09-29 08:13 UTC
**Could not see more number of messages in new discover**
In new discover we can see only few lines of seaerch results and scroling is limited to that widget only.
Old widget entire screen is getting scrolled and we are able to see more no of messages and easier .

**Comment by ashwin-pc** [comment] 2023-09-29 18:40
Closing as a duplicate of #5137

**Closed by ashwin-pc** 2023-09-29 18:40 UTC
Labels: bug, untriaged
