### ISSUE TITLE
[BUG] Dashboards fails to come up on main 

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/OpenSearch-Dashboards#5952] opened 2024-02-26 17:07 UTC
**Describe the bug**
OSD doesn't come up healthy when running the built artifact:

`{"type":"log","@timestamp":"2024-02-26T15:44:26Z","tags":["fatal","root"],"pid":4346,"message":"Error: Cannot find module './authentication_methods_registry.mock'\nRequire stack:\n- /home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/plugins/data_source/server/auth_registry/index.js\n- /home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/plugins/data_source/server/plugin.js\n- /home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/plugins/data_source/server/index.js\n- /home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/plugins/plugin.js\n- /home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/plugins/discovery/plugins_discovery.js\n- /home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/plugins/discovery/index.js\n- /home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/plugins/plugins_service.js\n- /home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/plugins/index.js\n- /home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/index.js\n- /home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/cli/serve/serve.js\n- /home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/cli/cli.js\n- /home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/cli/dist.js\n    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)\n    at Module.Hook._require.Module.require (/home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/node_modules/require-in-the-middle/index.js:61:29)\n    at require (node:internal/modules/helpers:177:18)\n    at Object.<anonymous> (/home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/plugins/data_source/server/auth_registry/index.js:25:41)\n    at Module._compile (node:internal/modules/cjs/loader:1356:14)\n    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1414:10)\n    at Module.load (node:internal/modules/cjs/loader:1197:32)\n    at Function.Module._load (node:internal/modules/cjs/loader:1013:12)\n    at Module.require (node:internal/modules/cjs/loader:1225:19)\n    at Module.Hook._require.Module.require (/home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/node_modules/require-in-the-middle/index.js:80:39) {\n  code: 'MODULE_NOT_FOUND',\n  requireStack: [\n    '/home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/plugins/data_source/server/auth_registry/index.js',\n    '/home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/plugins/data_source/server/plugin.js',\n    '/home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/plugins/data_source/server/index.js',\n    '/home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/plugins/plugin.js',\n    '/home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/plugins/discovery/plugins_discovery.js',\n    '/home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/plugins/discovery/index.js',\n    '/home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/plugins/plugins_service.js',\n    '/home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/plugins/index.js',\n    '/home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/core/server/index.js',\n    '/home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/cli/serve/serve.js',\n    '/home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/cli/cli.js',\n    '/home/runner/work/index-management-dashboards-plugin/index-management-dashboards-plugin/opensearch-dashboards-3.0.0-linux-x64/src/cli/dist.js'\n  ]\n}"}`

https://github.com/opensearch-project/index-management-dashboards-plugin/pull/999#issuecomment-1964470789

**To Reproduce**

**Expected behavior**

**OpenSearch Version**
Please list the version of OpenSearch being used.

**Dashboards Version**
Please list the version of OpenSearch Dashboards being used.

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**
 - Browser and version [e.g. 22]

**Additional context**

**Comment by derek-ho** [comment] 2024-02-26 17:08
@bandinib-amzn can you take a look? This issue seems to have something to do with `authentication_methods_registry.mock`, which I see you added to core recently.

**Comment by bandinib-amzn** [comment] 2024-02-27 18:04
Taking a look.

**Comment by bandinib-amzn** [comment] 2024-02-27 18:26
@derek-ho Which command gives this error? I'm unable to reproduce the issue. Also while merging PR all checks were successful. But checking about log I think https://github.com/bandinib-amzn/OpenSearch-Dashboards/blob/main/src/plugins/data_source/server/auth_registry/index.ts#L11 this line could be causing issue.

**Comment by bandinib-amzn** [comment] 2024-02-27 18:32
Thanks @derek-ho. Raising PR for fix shortly.

**Comment by bandinib-amzn** [comment] 2024-02-27 20:09
PR #5970 for fix has been merged to main branch.

**Comment by bandinib-amzn** [comment] 2024-02-28 01:33
Fixed issue.

**Closed by bandinib-amzn** 2024-02-28 01:33 UTC
Labels: bug
