### ISSUE TITLE
Stack Monitoring

### ISSUE THREAD

**Issue by saeed-mcu** [opensearch-project/OpenSearch-Dashboards#5121] opened 2023-09-12 21:30 UTC
Is there any plan to include **StackMonitoring** into the Opensearch and Opensearch dashboards, 
something similar to what Kibana has?
It is very useful for monitoring and tuning Opensearch (for e.g indexing rate ,  JVM Heap and ...)

**Comment by joshuarrrr** [comment] 2023-10-02 16:23
@saeed-mcu Agreed that it would make lots of sense for OpenSearch Dashboards to support the ability to self-monitor. I know it's something we've talked about in the past, but I'll let @mnkugler and @kgcreative weigh in on where it might fit in our overall priority roadmap.

**Comment by joshuarrrr** [comment] 2023-10-02 16:25
I'm going to close this as a duplicate of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3852

@saeed-mcu Also check out https://github.com/opensearch-project/OpenSearch-Dashboards/issues/3972 for some current alternatives.

**Closed by joshuarrrr** 2023-10-02 16:25 UTC
Labels: enhancement
