### ISSUE TITLE
[BUG] Unable to search for index patterns on Discover Menu through keywords

### ISSUE THREAD

**Issue by vmm-afonso** [opensearch-project/OpenSearch-Dashboards#5681] opened 2024-01-11 10:22 UTC
**Describe the bug**

I can't search for index patterns on the Discover Menu simply by typing keywords and get relevant search results…

It just turns those keywords bold (which makes it a bit easier to identify when looking for the right index pattern) but I still have to scroll down and look for the right index pattern.

I got the confirmation from a member on the opensearch-forum that this wasn't an issue in the previous version of Discovery and he gave me the green light to report this issue further

**To Reproduce**
1. Go to the 'Discover' Menu 
2. Try searching for any index pattern
3. Notice that by pressing enter you're not getting relevant search results, you're just seeing the parts of the indices that match your search turning bold

**Expected behavior**
I was expecting to get a list of indices that matched my search

**OpenSearch Version**
2.11.1

**Dashboards Version**
2.11.1

**Additional context**
Topic opened on the Opensearch forum (https://forum.opensearch.org/t/unable-to-search-for-index-patterns-on-discover-menu-through-keywords/17368)

**Comment by ashwin-pc** [comment] 2024-01-18 00:30
This is a duplicate of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5533 and is fixed in https://github.com/opensearch-project/OpenSearch-Dashboards/pull/5484

**Closed by ashwin-pc** 2024-01-18 00:30 UTC
Labels: bug, discover, v2.12.0
