### ISSUE TITLE
[Data explorer] Add filtering on index pattern selector

### ISSUE THREAD

**Issue by spapadop** [opensearch-project/OpenSearch-Dashboards#5419] opened 2023-11-02 09:01 UTC
**Is your feature request related to a problem? Please describe.**

When having many index patterns in a cluster, the strategy of highlighting the typed text on the big list of index patterns is not ideal.
Previously, when typing something, the drop-down list would appear only index patterns that contain the typed text. Now it always show all of them, and just highlights the typed text. 
![Screenshot 2023-11-02 at 09 56 00](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/5896507/39913e2c-1cbf-46b3-9331-3f6ea40079e1)

**Describe the solution you'd like**

in this case, the typed text is at the very bottom of the list, so I need to scroll all the way down. Having a filtering mechanism instead of the highlighting one that exists now, it would show only that "monit_qa_alarm*" index pattern immediately, hiding all the rest irrelevant index patterns.
![Screenshot 2023-11-02 at 09 56 04](https://github.com/opensearch-project/OpenSearch-Dashboards/assets/5896507/72778b61-6c27-4b73-97eb-4240f243302f)

**Comment by wbeckler** [comment] 2023-11-03 01:35
This looks like a Discover-related regression

**Comment by wbeckler** [comment] 2023-11-03 01:47
This is a dupe of https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5319

**Closed by wbeckler** 2023-11-03 01:47 UTC
Labels: bug

**Comment by wbeckler** [comment] 2023-11-03 01:48
Please reopen if this doesn't seem correct.
